### ISSUE TITLE
Snap Window

### ISSUE THREAD

**Issue by frostmorn** [telegramdesktop/tdesktop#10348]
### Steps to reproduce
1. Open conversation with somenone
2. Try to snap window to any screen side.

### Expected behaviour
Window snaps to part of the screen where I move it

### Actual behaviour
Window snaps to mouse pointer -_-

### Configuration
**Operating system:**
 OS: Arch Linux x86_64
 DE: MATE 1.24.1-1 
 
**Version of Telegram Desktop:**
2.5.1 & 2.5.8-1
**Installation source (Linux Only)** -
community arch repo

**Comment by ilya-fedin** [comment]
Can't reproduce with NixOS, MATE 1.24.1 and tdesktop 2.5.8 from https://desktop.telegram.org, snaps just fine

**Comment by frostmorn** [comment]
Just noticed, it happens when conversation with someone opened. Added.

**Comment by ilya-fedin** [comment]
Your report is still about old version of tdesktop, only latest version is supported

**Comment by frostmorn** [comment]
Updated to 2.5.8-1. Still bugs. Seems both versions affected. Added.

**Comment by ilya-fedin** [comment]
Looks like this is a bug between Qt/marco interaction. Looks like Qt starts to receiving events randomly after QWindow::startSystemMove call, so if Qt doesn't receive event of mouse button release, but receives event of mouse move, it sends a MouseMove event with QMouseEvent::buttons set to Qt::LeftButton and tdesktop code calls startSystemMove again. I'm afraid there could be nothing done from tdesktop side since events are just being skipped.

**Comment by frostmorn** [comment]
Sounds really bad, cause it worked okay earlier. Maybe someone will find solution, I hope.

This happens after u open conversation with someone, so, I expect something bad happens actually here.

**Comment by ilya-fedin** [comment]
Looks like I found some report of this on Qt bugtracker: https://bugreports.qt.io/browse/QTBUG-68501
startSystemMove/startSystemResize were private APIs at the time of the report and looks like they decided to just hack this on QSizeGrip side (looks like they added a check for QMouseEvent::buttons just like we have, but it doesn't help when snapping to edges for some reason). But they are public APIs now and the bug still exists...

> This happens after u open conversation with someone, so, I expect something bad happens actually here.

No, it doesn't depend on open conversation. It just happens randomly.

> Maybe someone will find solution, I hope.

Probably not if no one will raise this to Qt developers.

**Comment by frostmorn** [comment]
Yep, this random happens for me every time, so looks I'm very lucky :D

**Comment by ilya-fedin** [comment]
I tried to report, but not sure if they accept it since I'm too lazy to write a minimal reproducer.
https://bugreports.qt.io/browse/QTBUG-91077

**Comment by frostmorn** [comment]
Thanks man, this shit must be fixed, cause it sucks ;)

**Comment by frostmorn** [comment]
Lol, cool way to resolve issues :D

**Comment by frostmorn** [comment]
If bug exists in Qt library, I expect that issue called by u 3rd party should exist in any kind of apps which use it. 
So the same behavior should be in half of apps installed on my machine, but therefore, I'm the one whose luckiness makes me to see that only in your app, and it doesn't happen anywhere else.
So, due to Occam's razor I expect that u r not using it properly, which causes a bug, so it can not be actually called 3rd party.

**Comment by ilya-fedin** [comment]
> If bug exists in Qt library, I expect that issue called by u 3rd party should exist in any kind of apps which use it.

Any kind of apps that use the affected API

**Comment by ilya-fedin** [comment]
> So, due to Occam's razor I expect that u r not using it properly, which causes a bug, so it can not be actually called 3rd party.

I don't see any point in a debate. You either propose a fix via PR or wait for a fix and answer to stale bot requests (if you're still interested in issue to be open).

**Comment by frostmorn** [comment]
I will wait for another project which will use Qt so extensive like tdesktop, maybe a few years pass and plasma-workspace could do that, so bug will be fixed.

> I don't see any point in a debate. 
Me too :)

**Comment by gbschenkel** [comment]
@ilya-fedin have you tried to use Qt 6.2 beta for build? Since Qt LTS version are only Commercial now, maybe it is already been fixed. From 5.15.12 to 5.15.15, they have fixed 460 bugs.
The version 6.2 will have mostly all modules available from 5.15. It's on beta 3 right now. Or maybe Qt 6.1 can do the job.

**Comment by ilya-fedin** [comment]
tdesktop can't use Qt 6, sorry

**Comment by gbschenkel** [comment]
You can try the Qt patched version from KDE
https://invent.kde.org/qt/qt/qt5.git

Em 29 de agosto de 2021 02:11:57 BRT, ilya-fedin ***@***.***> escreveu:

**Comment by ilya-fedin** [comment]
No, thanks, tdesktop has its own patchset

**Comment by Vance-ng-vn** [comment]
I try with this action, and now bug was fixed!
Settings > Advanced > Enable "System Windows Frame"

**Comment by ilya-fedin** [comment]
> have you tried to use Qt 6.2 beta for build?

Current beta version uses Qt 6.2.0 and the bug is still present

**Comment by asy972** [comment]
I confirm the existence of a problem with the precompiled binary installation too (3.3 now). Moreover, today was case when mouse operation was partially blocked until xorg rebooted.

**Comment by adrian-the-git** [comment]
@asy972 when you experience this behavior, does pressing the escape key correct it?

**Comment by Germano0** [comment]
@adrian-the-git when Telegram got stick at the mouse pointer, I pressed escape key and it has gone back to normal

**Comment by chojnicki** [comment]
Year passed and nothing. Anyone is doing something with this? It's so annoying. I had to uninstall Telegram because of that and use smartphone instead, it's not use able on Linux Mint at least.

**Comment by Germano0** [comment]
@ilya-fedin what is the URL of the Qt bugreport?

**Comment by ilya-fedin** [comment]
https://github.com/telegramdesktop/tdesktop/issues/10348#issuecomment-776998754
It's marked as fixed although I pointed that they made the issue even worse at Qt dev branch, but the ignore me.

**Comment by ilya-fedin** [comment]
So I checked Qt 6.3 and the behavior has changed. I'm not sure whether it's better or worse, though.

**Comment by Qunas101** [comment]
Just experienced this bug for the first time in 4 months of using Manjaro/KDE

A workaround I have found is opening Telegram in fullscreen mode (full fullscreen, the one without a taskbar) that way Telegram is forced to stay in place, than you can navigate in settings and check "Use system window tray". With that Telegram works just fine, apart from an ugly message counter on top.

Is this bug permanent? How did I not experience it in such a long time?

**Comment by adrian-the-git** [comment]
@Qunas101 is this bug easily reproducible? For example, will I easily encounter it under KDE running on the Manjaro live environment?

**Comment by Qunas101** [comment]
Well, like I said, I encountered it for the first time in 4 months. Then it just randomly happened. It persists through reboots, it comes back if I uncheck "Use system window tray". There's no real way to get rid of it to try and reproduce it

Also, one more weird thing that happened with this bug: Telegram window got resized and notification settings seem to have reset. Really not sure how it's all connected

**Comment by ilya-fedin** [comment]
Here's the new Qt bug report I created for this issue. If someone experiences this problem on DE other then MATE, please write a comment there, this maybe this would add priority
https://bugreports.qt.io/browse/QTBUG-102488

**Comment by escape0707** [comment]
I'm on Arch, Gnome, Qt6, Wayland. And I can't even maximize the window now.

The windows won't snap to the boundary of my screen, too.
