### ISSUE TITLE
Window is not resized / text input box not kept visible while full-screen and virtual keyboard is shown

### ISSUE THREAD

**Issue by LuKePicci** [telegramdesktop/tdesktop#1297]
Putting tdesktop in full-screen view, opening the virtual keyboard does not move up the message input textfield making the client practically unusable. Moreover, Windows 10 always keeps desktop apps in full-screen mode while Tablet Mode is active.

**Comment by xcover** [comment]
![screenshot 6](https://cloud.githubusercontent.com/assets/3148313/11318458/cba8d618-9052-11e5-9e1c-d8152ca96de8.png)

**Comment by Aokromes** [comment]
Maybe a setting can be added to put write place to top instead bottom?

**Comment by Aokromes** [comment]
BTW, windows 10 users: feedback-hub:?contextid=123&feedbackid=637eda35-23d6-47d6-a7ea-ad455b2cbe6f&form=1&src=2

**Comment by midi1996** [comment]
this is one of the issues that bugs me a lot. hope they either fix it, m$ fix it or they make a UWP app.

**Comment by Aokromes** [comment]
http://aka.ms/Hssw2i upvote here.

**Comment by rdrrdl** [comment]
https://github.com/NXij/tdesktop-dark

here the problem was fixed

**Comment by LuKePicci** [comment]
Honestly I solved this issue by switching to Unigram while my convertible isn't docked, it's still buggy but at least is usable in touch scenario.

**Comment by surashu** [comment]
Any update on this? I would have opted to use Unigram like @LuKePicci said but it's still not as stable as the official desktop one. I also wish there was a way to revert to the old UI like is shown in the screenshot by @flippinger. If anyone knows a fork for this that's updated please do tell. The fork that @rdrrdl suggested is outdated and doesn't seem to be going to be updated any time soon. (It also has the old UI too, shame)

**Comment by LuKePicci** [comment]
Unigram just ended the alpha stage, now it's in beta and is much more stable. I definitely switched to it a couple of months ago.

**Comment by surashu** [comment]
I did too, but it still suffers from delayed notifications and some awkward UX implementations.

**Comment by Aokromes** [comment]
I wonder if this can be used as alternative:
https://doc.qt.io/qt-5.10/qtvirtualkeyboard-index.html
https://github.com/KDAB/virtual-keyboard-demo

**Comment by davidegiacometti** [comment]
Any update on this?

**Comment by felnix96** [comment]
Problem still persistent and regularly makes me want to switch to unigram. I wonder why this has no priority at all.

**Comment by LuKePicci** [comment]
This was an issue when there was no valid windows optimized app alternative. Now Unigram works at least 40 times better then two years ago. If this wasn't an high priority issue 4 years ago when tdesktop was the only windows telegram client, now this could also be closed since nobody should really care of optimizing this old good app. This project is built on cross-platform frameworks with well-known limits. Since the personal computing world evolved from the beginning of touch era in windows 8, the other platforms targeted by such frameworks did not follow the same evolution, so I presume it's rather difficult to approach such major usability issues with cross-platform limits. "Mouse + keyboard+ display only screen" is a mature enough combo, cross-platform UI frameworks do support it, but whatever comes later on, touch, pen, docking, AR, gaming consoles, phones .. this project has no way out.

**Comment by felnix96** [comment]
You got a point there. Thank you for clarifying that to me. I am totally not into the used cross-platform technique.
