### ISSUE TITLE
Ambiguous actions (for a contact)

### ISSUE THREAD

**Issue by magicgoose** [telegramdesktop/tdesktop#1407]
![screen shot 2015-12-16 at 5 02 00 pm](https://cloud.githubusercontent.com/assets/1442206/11842803/1c9b5b4a-a417-11e5-86ab-78deef3c7d3c.png)
It's not clear at all what's the difference between those 2 actions (annotated with arrows on the screenshot above).

The texts in their confirmations dialogs are also exactly the same.

**Comment by diazbastian** [comment]
@magicgoose 
*Clear history* delete the conversation history and maintains contact in the list (useful if you only have their alias)
*Delete conversation* delete the contact and full history.

They are very different things.
Cheers

**Comment by magicgoose** [comment]
@diazbastian 
Thanks for the explanation. But the descriptions in the Telegram's UI do not say anything about this, this should be fixed.

**Comment by masc3d** [comment]
+1 for cleaning this up, the two functions are redundant and confusing, while an option for simply closing an (inactive) chat session is missing.

why not simply have:
* _Close_: remove an inactive conversation from _Chats_ which could be reopened from the contact list without losing the history
* _Delete_:  close and delete the history

**Comment by Aokromes** [comment]
now it's clear history and delete chat, this issue is still valid?

**Comment by magicgoose** [comment]
The only thing that changed about this since the issue was opened is that the word "conversation" was replaced with "chat". So if it was valid in 2015, it's also valid now.
