### ISSUE TITLE
2000MB sized files won't upload as albums

### ISSUE THREAD

**Issue by theelectricsoul** [telegramdesktop/tdesktop#16845]
### Steps to reproduce
Upload 24 2000MB (2.097.152.00 Byte) sized files as an album, by drag and drop.

### Expected behaviour
TG should upload the first 10 files, then make it avaiable in the chat. Then it should upload the next batch of 10, make it avaiable, and then the last 4 files

### Actual behaviour
The whole upload finishes and only the last batch of 4 files is made available in the chat. In the screenshot you see a failed upload of 20 files. Only the last batch(10 files) was made available in the chat. 
![ZoomIt64_2021-08-23_11-09-02](https://user-images.githubusercontent.com/10260832/130421458-ba210554-9023-4360-b26d-6b82796ee02c.png)

### Hint
I tested it with 24 small pdf files. This works. My upload speed is 3MB/sec

### Configuration
**Operating system:**
Microsoft Windows Server 2016 Standard
Version	10.0.14393 Build 14393

**Version of Telegram Desktop:**
2.9

**Used theme**:
Classic

**Comment by john-preston** [comment]
log.txt? I think that maybe the server starts forgetting parts of the first files (with some FILE_PART_X_MISSING errors) or decides, that file references expired (FILE_REFERENCE_EXPIRED), I'd like to see at least log.txt after the issue was reproduced, or maybe even DebugLogs (sent in private), to see the exact response to messages.sendMultiMedia request in that case.

**Comment by theelectricsoul** [comment]
[log.txt](https://github.com/telegramdesktop/tdesktop/files/7070555/log.txt)

**Comment by theelectricsoul** [comment]
Plus video
https://user-images.githubusercontent.com/10260832/131214886-4f641c93-83e0-4733-8d33-487fa170ef1c.mp4

**Comment by john-preston** [comment]
@theelectricsoul I was told that it should be fixed on the server side. Can you check and confirm please?

**Comment by theelectricsoul** [comment]
> @theelectricsoul I was told that it should be fixed on the server side. Can you check and confirm please?

Sry.. I gave your message a thumbs up, just to acknowledge your request. Anyways...   the upload is still ongoing. The first batch of 10 files is still not posted. Tells me, there is still a problem.
![zoomit](https://user-images.githubusercontent.com/10260832/131736425-55d5f4c6-7a60-469b-a4ae-b84280b159ad.png)

I will report further after the upload finishes.

**Comment by john-preston** [comment]
@theelectricsoul Then I'll ask for log.txt from that launch (and the time when ten of files in an album finished uploading). Maybe I'll have to ask for DebugLogs (which contain records of all network activity, so I'll ask then in private), if you're willing to debug it further.

**Comment by theelectricsoul** [comment]
@john-preston 

let's go.....    how to create DebugLogs?

**Comment by theelectricsoul** [comment]
[log.txt](https://github.com/telegramdesktop/tdesktop/files/7096907/log.txt)
@john-preston

**Comment by john-preston** [comment]
@theelectricsoul Should be fixed now.

**Comment by theelectricsoul** [comment]
@john-preston 
is fixed. :)
