### ISSUE TITLE
Tray icon not displaying in Lubuntu 15.10 wily

### ISSUE THREAD

**Issue by dminca** [telegramdesktop/tdesktop#1716]
**OS:** Lubuntu 15.10 - wily
**Kernel version:** 4.2.0-30-generic

----

![Telegram icon on the right](https://cloud.githubusercontent.com/assets/5355219/13456823/ab803a5a-e06d-11e5-91c9-186a1c4b7204.png)

## Actual result
Lubuntu fallback icon is used

## Expected result
Telegram default icon app should be used
![Telegram default icon](https://cloud.githubusercontent.com/assets/5355219/13456956/35751258-e06e-11e5-8a9b-affc1a930c2e.png)

## Processes involved
- [LXPanel 0.8.1][1]
- [gtk-update-icon-cache][2] - command issued to update icon cache

## Other details
Telegram's icon is located in `$HOME/.icons/telegram.png` but I don't know how to configure it to display properly in the tray

**Related:** #1653

[1]: http://lxde.org/
[2]: https://developer.gnome.org/gtk3/stable/gtk-update-icon-cache.html

**Comment by Arcaena** [comment]
I'm pretty sure this is an lxde problem since it works fine for me in gnome, xfce, i3, and awesome. 

(although as an aside, sometimes the telegram icon gets corrupted (?) and looks like it got vomited on)

**Comment by dminca** [comment]
It is an LXDE Panel problem for sure, but so far I've tried placing the icon in LXDE default folder for tray png's and no result... 
Don't know what else to try

**Comment by Aokromes** [comment]
#1530

**Comment by dminca** [comment]
### Testing phase 2
I've saw that _Skype_ icon works perfectly (even when I put myself in Busy or Away, it changes).

Googled the crap out of _LXDE Tray icon changing_ and I [found that][1] I need to update icon cache everytime I change someting in the **icons directory**.

#### Did a search for skype icons in the terminal
```sh
➜  ~  locate skype | grep png                  
/usr/share/icons/hicolor/128x128/apps/skype.png
/usr/share/icons/hicolor/16x16/apps/skype.png  
/usr/share/icons/hicolor/24x24/apps/skype.png  
/usr/share/icons/hicolor/256x256/apps/skype.png
/usr/share/icons/hicolor/32x32/apps/skype.png  
/usr/share/icons/hicolor/48x48/apps/skype.png  
/usr/share/icons/hicolor/64x64/apps/skype.png  
/usr/share/icons/hicolor/96x96/apps/skype.png  
/usr/share/pixmaps/skype.png                   
```
So far, i've tried:
- [x] copy a 48x48 `telegram.png` in `~/.icons/` [ failed ]
- [x] copy 48x48 `telegram.png` in `/usr/share/pixmaps` [ failed ]
- [x] copy 48x48 `telegram.png` in `/usr/share/icons/hicolor/48x48/apps/` [ failed ]
- [x] copy 256x256 icon in `/usr/share/icons/hicolor/256x256/apps/` [ failed ]
- [ ] copy 16x16 icon in `/usr/share/icons/hicolor/16x16/apps/`
- [ ] copy 22x22 icon in `/usr/.../22x22/apps/`
- [ ] copy 32x32 icon in `/usr/.../32x32/apps/`

After each copy/paste in folder, I'd trigger `gtk-update-icon-cache-3.0` with my Telegram closed, and then reopened Telegram to see if it's changed.

[telegram48x48](https://cloud.githubusercontent.com/assets/5355219/13569228/762e4882-e46f-11e5-8fbf-1eef396aafa3.png)
[telegram256x256](https://cloud.githubusercontent.com/assets/5355219/13569229/7645c4ee-e46f-11e5-94c9-44144de3a92c.png)

[1]: http://www.pclinuxos.com/forum/index.php/topic,101782.msg871545.html?PHPSESSID=287h1fpet7em0qeg4uh7g7p6a4#msg871545

**Comment by Israel-** [comment]
@dminca I got the e-mail on the Lubuntu list, but decided to reply here.
Have you tried using a different icon theme?
Also, apps should install icons into the hicolor/48x48/apps directory
https://specifications.freedesktop.org/icon-theme-spec/latest/ar01s07.html
The issue might be that the Lubuntu Box theme is overriding the default icon.

I don't know enough about Qt tray icons to say much about how the program determines the icon name.

Changing the desktop file will only effect the menus, not tray icons.

**Comment by dminca** [comment]
Thank you for the fast reply @Israel- 
* I haven't tried switching the icon theme;
* I've tried placing the icons in their designated folders as you can see above, and all of my trials sadly **failed**
* awkward is that Skype icons function properly, even when I change status (I know this has something to do with Skype codebase to change icon on different statuses)

**Comment by Israel-** [comment]
@dminca it may be that skype icons are not themed by icon themers, or that they hard code paths (bad)
And from your locate search it seems that Skype status icons are not listed... they may even be xpm data that is included in the program.
Try changing the theme to hicolor and see if it uses the default icons.

**Comment by dminca** [comment]
@Israel- how do I change theme to hicolor?

**Comment by Israel-** [comment]
there is the app lxappearance sorry I can't remember the menu name off hand... something like "Change Look and Feel"

**Comment by dminca** [comment]
I've checked that and I have no **hicolor** icon theme
![2016-03-22-182347_590x475_scrot](https://cloud.githubusercontent.com/assets/5355219/13959075/3b34e9c8-f05b-11e5-84cb-1bed1be8a2e7.png)

**Comment by Israel-** [comment]
Oh... try GNOME or one of the others... yeah I guess hicolor is mostly an inherited theme

**Comment by dminca** [comment]
Sorry but I'm not switching Desktop environments to fix a Tray icon bug lol
Ok, thanks anyway, will keep looking for solutions/suggestions.

**Comment by Israel-** [comment]
@dminca you can switch to the GNOME theme, not the DE.  It is listed above in lxappearance.  Simple misunderstanding.
You could try Humanity if you are completely opposed to anything related to GNOME :smile:

**Comment by dminca** [comment]
LOL @Israel- sorry, didn't mean to sound harsh, I thought you were referring to the DE :stuck_out_tongue_winking_eye: 
ok, will give that a shot :smiley:

**Comment by its-thomas** [comment]
Same problem in a brand new installation of Lubuntu 16.04 (64-Bit). Any news on this issue?

**Comment by feer9** [comment]
Do you still have that problem? Same here with lubuntu 15.10

**Comment by dminca** [comment]
Yes. Problem still occurs.

On Wed, May 4, 2016, 05:22 feer9 <notifications@github.com> wrote:

> Do you still have that problem? Same here with lubuntu 15.10
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/telegramdesktop/tdesktop/issues/1716#issuecomment-216725295>
>
-- 
Daniel Andrei Mincă
GPG Key fingerprint = C4A3 8F02 9F1F 6567 6957 BC34 90CD 7C62 81DF 875D

**Comment by maclaine1138** [comment]
I saw a tip [here](http://ubuntu-mate.community/t/dropbox-issue-on-ubuntu-mate-15-10-and-16-04-beta/3546/21) which solved the problem for me (I'm using Lubuntu 16.04 LTS), although I have no idea why. I launched Telegram using the command

`~$ dbus-launch /PATH/Telegram start`

and this appeared finally:

![2016-05-14-121750_1024x600_scrot](https://cloud.githubusercontent.com/assets/19362716/15269189/2eaf0ebc-19ce-11e6-8239-897bfadb76dc.png)

Hope this helps.

**Comment by feer9** [comment]
Thanks so much, it works! And When you left click on the icon, it now open the app, not showing the contextual menu lol

**Comment by dminca** [comment]
@maclaine1138 thanks man! That solved it, now I'll just map the Shortcut with that command
`dbus-launch ~/Downloads/Telegram/Telegram start`

**Comment by ovrmn** [comment]
And you do not have annoying that after the closing of telegram app in the system remains hanging dbus-daemon, which consumes the memory, that means you will kill it manually every time or exit session? Great.

**Comment by Gameranand** [comment]
dbus-launch ~/Downloads/Telegram/Telegram start

This command does works but I am not able to create a shortcut.

**Comment by dminca** [comment]
@ovrmn how do you solve the issue then?
@Gameranand what shortcut? Where?

**Comment by Gameranand** [comment]
@dminca 
I mean I wanted to create a shortcut in Start Menu of Linux Mint LMDE2 Cinnamon 64 bit Edition. But when I make it through the Menu, shortcut is created just fine but it won't do anything. I also tried to add it to startup with the command to see if it executes in the terminal without manual intervention at all.
It didn't.
So I just added disown at the end to make the command like this.
dbus-launch ~/.softwares/Telegram/Telegram start & disown

Now I just start it in terminal and close the terminal. Its not an annoyance for me because I use Telegram for all the communication so its open as long as PC is open. But the shortcut thing is not working at all.

**Comment by dminca** [comment]
For everyone who's interested. The tray-icon issue is fixed now.
I'm running on `Ubuntu 16.04 xenial`, Telegram Desktop version `1.0.2`

**Comment by badbod** [comment]
HI, I am using latest ver Telegram and Lubuntu 17.10 and still seeing this issue,

**Comment by Translator5** [comment]
Manjaro Linux (latest 17-05-2017)
Cinnamon DE
Telegam 1.2.17
Full missing Tray icon, but context menu works (invisible icon)
