### ISSUE TITLE
Crash on starting video in group chat (MacOS X 10.15.7)

### ISSUE THREAD

**Issue by JFC-MC** [telegramdesktop/tdesktop#17420]
Hello!
There's an issue which can be reproduced: every time when I enable video in group chat Telegram Desktop crashes leaving no trace in log.txt (even with debugmode enabled).

Could you please fix that?

Versions info:
Telegram 3.3
MacOS X 10.15.7

Removing  profile directory (~/Library/Application Support/Telegram Desktop) doesn't solve the issue.

**Comment by Woundorf** [comment]
This also happens to me with Telegram 3.3 on macOS 10.13.6. It also crashes when receiving a video call (no need to answer), as in #17392, and when opening the call settings in advanced configuration.

log.txt also doesn't say anything about the crash, but in the Mac bug reporting tool I can get the following error details (these are for the call settings crash):

> Application Specific Information:
> *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'The activeVideoMaxFrameDuration passed is not supported by the device.  Use -activeFormat.videoSupportedFrameRateRanges to discover valid ranges.'
> abort() called
> terminating with uncaught exception of type NSException

Also the following backtraces (only the part that seems relevant):

> Application Specific Backtrace 1:
> 0   CoreFoundation                      0x00007fff4d96466b __exceptionPreprocess + 171
> 1   libobjc.A.dylib                     0x00007fff74bbb942 objc_exception_throw + 48
> 2   AVFoundation                        0x00007fff498a9acf -[AVCaptureDALDevice transportType] + 0
> 3   Telegram                            0x0000000108eff539 Telegram + 77186361
> 4   Telegram                            0x0000000108efdc27 Telegram + 77179943
> 5   Telegram                            0x0000000108f00b90 Telegram + 77192080
> 6   Telegram                            0x0000000108f02f4c Telegram + 77201228
> [...]

> Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
> 0   libsystem_kernel.dylib          0x00007fff75922b66 __pthread_kill + 10
> 1   libsystem_pthread.dylib         0x00007fff75aed080 pthread_kill + 333
> 2   libsystem_c.dylib               0x00007fff7587e24d __abort + 144
> 3   libsystem_c.dylib               0x00007fff7587e1bd abort + 142
> 4   libc++abi.dylib                 0x00007fff7377bf8f abort_message + 245
> 5   libc++abi.dylib                 0x00007fff7377c12b default_terminate_handler() + 265
> 6   libobjc.A.dylib                 0x00007fff74bbda47 _objc_terminate() + 97
> 7   libc++abi.dylib                 0x00007fff737977c9 std::__terminate(void (*)()) + 8
> 8   libc++abi.dylib                 0x00007fff7379726f __cxa_throw + 121
> 9   libobjc.A.dylib                 0x00007fff74bbba71 objc_exception_throw + 351
> 10  com.apple.avfoundation          0x00007fff498a9acf -[AVCaptureDALDevice setActiveVideoMaxFrameDuration:] + 562
> 11  com.tdesktop.Telegram           0x0000000108eff539 0x104563000 + 77186361
> 12  com.tdesktop.Telegram           0x0000000108efdc27 0x104563000 + 77179943
> 13  com.tdesktop.Telegram           0x0000000108f00b90 0x104563000 + 77192080
> 14  com.tdesktop.Telegram           0x0000000108f02f4c 0x104563000 + 77201228
> [...]

**Comment by Aokromes** [comment]
enable beta and on next start post crash id here.

**Comment by Woundorf** [comment]
Crash id: 293c72ba-3125-4e71-97ec-599d24394059

**Comment by john-preston** [comment]
Thanks for your report! I hope it'll be fixed in the next version.

**Comment by Woundorf** [comment]
Hi, I now have the latest beta (3.3.1 beta) that includes this fix but it still crashes with the same error about the max frame duration. I have sent another crash: 3097fc0d-7932-4ed6-a021-9e6bf613a644.

**Comment by john-preston** [comment]
@Woundorf Thanks, I think I see how this is (incorrectly) fixed. If I build a test version will you be able to check if it works?

**Comment by john-preston** [comment]
You can contact me at t.me/preston

**Comment by Woundorf** [comment]
Yes, I can try. I will contact you on Telegram.

**Comment by john-preston** [comment]
Should be fine now.
