### ISSUE TITLE
[Bug] permanent sound output  // not critical

### ISSUE THREAD

**Issue by ChrisCA** [telegramdesktop/tdesktop#179]
If Telegram is running, there is a permanent sound output via digital audio.
I use a "Teufel 5.1 Soundsystem with Decoderstation 5".
Normally, Windows doesn't send any digital sound data if there is no aktiv sound output from e.g. a movie or music file. So the decoder station says "no signal".
If Telegram is running, there is a permanent sound output.
Decoder station says, that audio data is playing.
There is no loud sound output but a static noise while Telegram is running.
Telegram stops sending digital sound if you close it completely via right click on taskbar icon.
Simply closing the window don't stops sending audio data.

This is not critical, but I thing it wasn't planned, and as I already said, there is a permanent sound output.
Maybe a bug from used sound library?

Please someone else test this with a digital sound system.

Telegram v. 0.5.21
Windows 8.1 64-bit
Teufel 5.1 soundsystem with Decoderstation 5
soundoutput via optic digital cable
Realtek audio driver v. 6.0.1.7083 (Audio Codec ALC887)
Motherboard Asus H87-Pro

**Comment by ChrisCA** [comment]
With "system sleep / hibernation fixed" in v. 0.7.7 this problem has been solved!

**Comment by mirhl** [comment]
I still have this problem. 
When audio note is finished windows mixer, indeed, shows no activity. 

But still, I have to restart the program to change audio output.

**Comment by telegramdesktop** [comment]
This issue is about permanent audio output. It does not change audio output device while running yet, but this is something other.

**Comment by ManuelSchneid3r** [comment]
Pulse Audio still permanently displays "telegram-dektop" as audio output.
telegram-desktop-bin 0.9.56
pulseaudio 9.0
