### ISSUE TITLE
Emoji panel merges with pinned message

### ISSUE THREAD

**Issue by formatq** [telegramdesktop/tdesktop#1982]
### Steps to reproduce
1. Pin some message
2. Resize the tdesktop to small size (height 476 px )
3. Open emoji panel

### Expected behaviour
Emoji panel should be on top

### Actual behaviour
Emoji panel merges with pinned message

### Configuration
**Operating system: Win10**

**Version of Telegram Desktop: 0.9.47 alpha**

**Comment by stek29** [comment]
Screenshot (Look at "X")
![screen shot 2016-05-04 at 12 34 25](https://cloud.githubusercontent.com/assets/11808223/15010418/f4e0624a-11fc-11e6-8968-23ebf0aaf3cf.png)

**Comment by john-preston** [comment]
Thanks for your report! This will be fixed in the next version.

**Comment by stek29** [comment]
@john-preston you said it's "already fixed in code" at 14th of April :)

**Comment by LucaRed** [comment]
This bug is still present, I can reproduce it on version **0.10.1** on **Linux 64 bit**.

**Comment by stek29** [comment]
@LucaRed screenshot?

**Comment by john-preston** [comment]
@stek29 This one should be fixed in alpha 0.10.2
