### ISSUE TITLE
Problem with draft sync feature

### ISSUE THREAD

**Issue by mikehaertl** [telegramdesktop/tdesktop#2229]
I think some time ago Telegram introduced a feature to sync draft messages between different devices. This doesn't work well for me. I use Telegram on 3 devices and sometimes when I open Telegram on my smartphone, the message input box is prefilled with the first sentence from a message I already sent long ago from Desktop
### Steps to reproduce

I don't have a recipe to reproduce. But I did something like the following:
1. Start typing a message in the Desktop client. You probably have to interrupt this and later continue to complete the message and send it
2. Write more messages
3. Open Telegram on another device
### Expected behaviour

It should not prefill the input box with draft messages that where already sent from another device.
### Actual behaviour

The input box is prefilled with the first sentence of an outdated draft message from the desktop. This is quite annoying as I first have to delete this message which can be cumbersome on mobile devices.
### Configuration

**Operating system:** Linux Mint 17.3

**Version of Telegram Desktop:** 0.9.56

**Comment by verokarhu** [comment]
This happens on Windows 10 on 0.9.56 as well. The other device is running Telegram for Android v 3.10.1 (821).

**Comment by serverx** [comment]
Ubuntu 16.04.1 with Telegram Desktop 0.9.56 affected.

**Comment by kastedo** [comment]
Same problem here, working with Ubuntu 16.04. I've been affected by this issue for several months now. All my Telegram installations are updated to the last version but the updates hasn't fixed it. It only happens with one particular message in one particular group. As @mikehaertl described above, that message was successfully sent long ago but it is reloaded as a draft over and over, no matter if I delete it, it will show up again every time I open the desktop client.

**Comment by StefanDesu** [comment]
I just found this thread via Google. I have the same issue, but using Telegram for macOS (not the universal one) and for iPhone. As development on this app is completely separate from the Telegram for macOS one (as far as I know), it might be a server issue. Just throwing it out there in the hopes that it'll get fixed one day.

**Comment by stek29** [comment]
@StefanDesu it's not a server issue, it's an issue on how apps handle "cloud drafts". I've made #3567 which should solve this issue for TDesktop.

**Comment by yourneko** [comment]
This issue appears on Telegram Desktop 1.1.10 and on updated iOS telegram. Any way to fix it?

**Comment by stek29** [comment]
@yourneko <kbd><kbd>Ctrl</kbd>/<kbd>CMD</kbd> + <kbd>Z</kbd></kbd> on TDesktop

**Comment by artamonovdev** [comment]
Same bug on Ubuntu 16.04.3

**Comment by stek29** [comment]
I'd call this a feature. Use "Cancel" if you want to recover text.

**Comment by mikehaertl** [comment]
@stek29 Did you carefully read the issue description? I don't think, this is any useful feature:

* You type and send a message on one device
* After some time you open another device and find the incomplete message as draft there.

Why would I ever want to see an old message that I sent some time ago?

I have to admit though, that for some time now I didn't see this problem anymore.

**Comment by stek29** [comment]
@mikehaertl Sorry, I've misread it, thought you were talking about drafts removing what you just wrote.

I'm still sure it's an API issue if it's still not fixed tho, maybe server doesn't send update for draft being cleared (on send?).

**Comment by artamonovdev** [comment]
Maybe need to disable message sync between PC and mobile phone? This is possyble?

**Comment by stek29** [comment]
should be fixed

**Comment by Midgaard94** [comment]
This still happens today on Telegram Desktop Win10 and Android

**Comment by mortezaataiy** [comment]
This still happens today on Telegram Desktop Ubuntu 18.04
