### ISSUE TITLE
Telegram hangs on W10 Anniversary Update

### ISSUE THREAD

**Issue by Z3phyr** [telegramdesktop/tdesktop#2296]
### Steps to reproduce
1. Get a message with notification
2. Try to interact with the program (while the notification is still on the screen)
### Expected behaviour

The program should work normally
### Actual behaviour

The program freezes and i have to kill it through task manager
### Configuration

**Operating system:**
W10 x64 Anniversary Update 1607 (14393.10)
**Version of Telegram Desktop:**
0.10

**Comment by john-preston** [comment]
@Z3phyr How do you get this update? I'm testing on Win10 Home 64 bit and it works fine.

Does it freeze if you disable "Window toast notifications" in Settings? (and receive a message with a custom app notification — white in the bottom-right corner). Or it freezes only after showing (or trying to show) a windows toast notification?

**Comment by spzSource** [comment]
@john-preston 

> How do you get this update?

Just in case, it's a new big update. You can download it through control panel ("Update & security") or manually [here ](https://support.microsoft.com/en-us/help/12387/windows-10-update-history?ocid=update_setting_client) .

**Comment by john-preston** [comment]
@spzSource System is up to date. Is it one of some Insider Preview builds?

**Comment by john-preston** [comment]
And is it working fine with custom notifications? Hanging only with Windows toast notifications?

**Comment by auchri** [comment]
@john-preston 

> System is up to date. Is it one of some Insider Preview builds?

No, the anniversary update is not available for all users yet.

**Comment by Z3phyr** [comment]
it's the latest update from Windows, not an insider build. The issue happens with system notifications I can't test the custom notifications right now, I'll update as soon as possible.

**Comment by john-preston** [comment]
@Z3phyr To test the custom notifications you just need to switch off Windows toast notifications in Settings.

**Comment by john-preston** [comment]
![image](https://cloud.githubusercontent.com/assets/17900494/17415387/8fabbffa-5a81-11e6-912b-74ba6c88e0b8.png)

:(

**Comment by DaFri-Nochiterov** [comment]
^ same thing, but without error code at all :sob:

**Comment by john-preston** [comment]
@DaFri-Nochiterov I've managed to update it, but in first couple of tests it works fine.

**Comment by marcogiorgio** [comment]
Hi, I have the same exact problem. I clean installed W10 anniversary, installed telegram, and when a message arrives, it oftens make Telegram crash. I have to force close it with the task manager.

**Comment by auchri** [comment]
@marcogiorgio 
Does it freeze if you disable "Window toast notifications" in Settings? (and receive a message with a custom app notification — white in the bottom-right corner). Or it freezes only after showing (or trying to show) a windows toast notification?

**Comment by marcogiorgio** [comment]
@auchri  Yes it happens with "Window toast notifications" on. If I disable it, it all seems normal

**Comment by auchri** [comment]
@marcogiorgio Thanks for the answer, so it seems to be an issue with the windows toast notifications @john-preston

**Comment by marcogiorgio** [comment]
@auchri I am glad I helped :)

**Comment by Zenexer** [comment]
Can confirm this issue has been present since early Insider builds of the Anniversary Update, but only for native toast notifications.  It's possible that it's been fixed in the latest update, though, as I wasn't able to reproduce it just now.  Normally those notifications crash Telegram quite consistently.

**Comment by sinaa** [comment]
Can also confirm the same exact issue since anniversary update.

**Comment by Zenexer** [comment]
Confirmed still an issue with 0.10.2 alpha.  Looking to debug.

**Comment by Zenexer** [comment]
Not getting anywhere debugging it.  As far as I can tell, the window continues to update; it just doesn't respond to any events.  There are events coming in from Windows that get processed, but I can't really tell if they're normal.  Sometimes when it got stuck the main thread was running `MainWindow::shadowsActivate` and was busy drawing.  Now I can't reproduce that; it's always stuck in the kernel, and Microsoft hasn't released the debug symbols for the Insider preview I'm using.  I tried profiling it but didn't see an excessive number of calls to anything at first glance.  I can only assuming it's waiting on something that usually never comes.

**Comment by yongjunjie** [comment]
Currently am facing the same issue too.

**Comment by ms82494** [comment]
Same issue for me. Turning off "Use Windows Notifications" seemed to take care of it. Thanks to @john-preston for isolating this issue!

**Comment by Alimirlou** [comment]
Still have this issue and it's not fixed even in the new version (0.10.5) yet...!

**Comment by john-preston** [comment]
@Alimirlou I can't reproduce that myself, but the collected data shows, that this is some problem inside the Windows notifications methods :(

I've asked about that on the msdn article about the toast notifications, but didn't get any response so far: https://blogs.msdn.microsoft.com/tiles_and_toasts/2015/10/16/quickstart-handling-toast-activations-from-win32-apps-in-windows-10/#comment-4485

Currently I can only suggest you disabling the windows toast notifications in Settings (so you'll get custom telegram notifications instead).

**Comment by Aenadon** [comment]
Since I'm on Win10 Anniversary, I got that issue too. Disabling Windows notifications got me rid of that issue.

**Comment by auchri** [comment]
@john-preston You should ask on the MSDN forums: https://social.msdn.microsoft.com/Forums/

**Comment by Zenexer** [comment]
Is there an easy way I can log all messages Qt receives from Windows?  I played around with various environment variables but couldn't get it working in a useful way.

I suspect the issue might not actually be with Windows, but rather Qt.  As far as I can tell, there's still a lot of drawing going on when Telegram freezes.  Either messages aren't making it to their proper destinations, or the message loop is getting stuck.

**Comment by dim5** [comment]
Can confirm that the issue is still present on 0.10.8 with the latest windows updates installed (KB3194496)

**Comment by john-preston** [comment]
@dim5 I'm afraid the only thing to do is to disable Windows toast notifications in Settings. They hang the process sometimes (as I see it in logs), no idea what I can do about it.

**Comment by VSG24** [comment]
Still crashes with latest version on a fully updated Windows 10.

**Comment by john-preston** [comment]
@VSG24 Please try latest alpha version.

**Comment by jgrondier** [comment]
The issue still persists on v0.10.19, and on two of my devices, one using Windows 10 Pro 64bits and the other Windows 10 Education 64bits.

It always happens when the app is minimized and I get a notification from a conversation which isn't the "opened" one.

**Comment by Marocco2** [comment]
Build 14959 no more issue

**Comment by juniberry** [comment]
I'm having this exact issue.... I'll get a message and Telegram will just deadlock ....done...... need to kill the process and restart it.. and I'm running Win10 AUP...  It started happening with the latest update.

**Comment by Sushubh** [comment]
Yup. I am on the alpha build and this was never fixed for me. I thought an update would arrive with a fix. It never did. I have to keep native notifications disabled because of this issue.

**Comment by john-preston** [comment]
@Sushubh Yes, because they freeze in Windows :( So I had to disable them by default.

**Comment by Marocco2** [comment]
Strange. I have Surface Pro 3 i5 with build 14971 and native notifications don't freeze telegram

**Comment by stek29** [comment]
@Marocco2 It's Insider build, isn't it?

**Comment by Marocco2** [comment]
Yes, it is

**Comment by stek29** [comment]
@Marocco2 so it means Microsoft fixed the issue.
But the fix isn't published yet, and majority of users are not Insidersz so it's better to keep them disabled by default.

**Comment by Marocco2** [comment]
Yeah, I agree

**Comment by ibrokemypie** [comment]
anyone know when this will be pushed to non insider? still problem on 1607

**Comment by Zenexer** [comment]
I'm not encountering it nearly as frequently now.

**Comment by stek29** [comment]
@ibrokemypie ask Microsoft. IMO it will be pushed with next major update like Creator's Update.

**Comment by john-preston** [comment]
I have information, that this should be fixed only in the Creators Update :(

**Comment by k0R73z** [comment]
Still have problem on 1.0.29

**Comment by juniberry** [comment]
I also still have this issue on 1.0.29 under Windows 10 Pro with the latest updates.

**Comment by auchri** [comment]
Please install the creators update

**Comment by seguemark** [comment]
Issue still exists (or exists again) in 1.1.19.

**Comment by ms82494** [comment]
I am running Windows 10 Pro and I use Wondows notifications on 1.1.19 without problems.

**Comment by T3rminat0r** [comment]
Win 10 Pro, Creators update, it IS in fact fixed, yep.

**Comment by win9z** [comment]
After telegram update i have same issue

Windows 10, build 1607
Telegram Desktop: 1.9.14

**Comment by Aokromes** [comment]
> After telegram update i have same issue
> Before update everything was okay for a two years
> 
> Windows 10, build 1607
> Telegram Desktop: 1.9.14

update to windows 10 build 1909.
