### ISSUE TITLE
Telegram crashes while receiving video call with enabled OpenGL setting

### ISSUE THREAD

**Issue by roman0x58** [telegramdesktop/tdesktop#25432]
### Steps to reproduce

1. Open Telegram
2. Go to Advanced settings and enable OpenGL for rendering media
3. Make a video call
4. The reciever accept the video call 
5. Application crashes

### Expected behaviour

The application should show the video/screenshare

### Actual behaviour

When video is activated the application crashes

### Operating system

ArchLinux, Gnome 43.1, wayland

### Version of Telegram Desktop

4.3.3

### Installation source

Static binary from official website

### Logs
System logs 
```
Nov 24 18:02:44 tuchka kernel: Telegram[67837]: segfault at 40 ip 00007f9e322e584d sp 00007ffdf21363f8 error 4 in libc.so.6[7f9e321b4000+15b000] likely on CPU 6 (core 12, socket 0)
Nov 24 18:02:44 tuchka kernel: Code: 00 00 00 00 00 66 66 2e 0f 1f 84 00 00 00 00 00 66 66 2e 0f 1f 84 00 00 00 00 00 66 90 f3 0f 1e fa 48 89 f8 48 83 fa 20 72 23 <c5> fe 6f 06 48 8>
Nov 24 18:02:44 tuchka kernel: audit: type=1701 audit(1669298564.523:551): auid=1000 uid=1000 gid=984 ses=4 pid=67837 comm="Telegram" exe="/usr/local/apps/Telegram/Telegram" sig=11 >
Nov 24 18:02:44 tuchka audit: BPF prog-id=130 op=LOAD
Nov 24 18:02:44 tuchka audit: BPF prog-id=131 op=LOAD
Nov 24 18:02:44 tuchka audit: BPF prog-id=132 op=LOAD
Nov 24 18:02:44 tuchka kernel: audit: type=1334 audit(1669298564.526:552): prog-id=130 op=LOAD
Nov 24 18:02:44 tuchka kernel: audit: type=1334 audit(1669298564.526:553): prog-id=131 op=LOAD
Nov 24 18:02:44 tuchka kernel: audit: type=1334 audit(1669298564.526:554): prog-id=132 op=LOAD
Nov 24 18:02:44 tuchka systemd[1]: Started Process Core Dump (PID 67982/UID 0).
Nov 24 18:02:44 tuchka audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@20-67982-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostnam>
Nov 24 18:02:44 tuchka kernel: audit: type=1130 audit(1669298564.556:555): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@20-67982-0 comm="systemd" exe="/usr/>
Nov 24 18:02:48 tuchka systemd-coredump[67983]: [🡕] Process 67837 (Telegram) of user 1000 dumped core.
                                                
                                                Stack trace of thread 67837:
                                                #0  0x00007f9e322e584d n/a (libc.so.6 + 0x15384d)
                                                #1  0x00007f9e0ba26fea n/a (iris_dri.so + 0x626fea)
                                                #2  0x00007f9e0b671535 n/a (iris_dri.so + 0x271535)
                                                #3  0x0000000002d00b17 n/a (Telegram + 0x2900b17)
                                                #4  0x00000000018ae9d4 n/a (Telegram + 0x14ae9d4)
                                                #5  0x0000000002c9bd52 n/a (Telegram + 0x289bd52)
                                                #6  0x0000000004c892c7 n/a (Telegram + 0x48892c7)
                                                #7  0x0000000004a6bd4b n/a (Telegram + 0x466bd4b)
                                                #8  0x0000000002d47005 n/a (Telegram + 0x2947005)
                                                #9  0x0000000004be177d n/a (Telegram + 0x47e177d)
                                                #10 0x0000000004be4f1e n/a (Telegram + 0x47e4f1e)
                                                #11 0x0000000001a19c6e n/a (Telegram + 0x1619c6e)
                                                #12 0x0000000005386d70 n/a (Telegram + 0x4f86d70)
                                                #13 0x0000000004bde9f3 n/a (Telegram + 0x47de9f3)
                                                #14 0x0000000004becb04 n/a (Telegram + 0x47ecb04)
                                                #15 0x0000000005c992e7 n/a (Telegram + 0x58992e7)
                                                #16 0x0000000005c9918b n/a (Telegram + 0x589918b)
                                                #17 0x0000000005c9918b n/a (Telegram + 0x589918b)
                                                #18 0x0000000005c9918b n/a (Telegram + 0x589918b)
                                                #19 0x0000000005c9918b n/a (Telegram + 0x589918b)
....
```
Telegram desktop logs
```
[2022.11.24 18:02:53] Launched version: 4003003, install beta: [TRUE], alpha: 0, debug mode: [FALSE]
[2022.11.24 18:02:53] Executable dir: /usr/local/apps/Telegram/, name: Telegram
[2022.11.24 18:02:53] Initial working dir: /home/roman/
[2022.11.24 18:02:53] Working dir: /home/roman/.local/share/TelegramDesktop/
[2022.11.24 18:02:53] Command line: /usr/local/apps/Telegram/Telegram --
[2022.11.24 18:02:53] Executable path before check: /usr/local/apps/Telegram/Telegram
[2022.11.24 18:02:53] Logs started
[2022.11.24 18:02:53] Launcher filename: org.telegram.desktop.4d625c0aa728af28d08c0a361a539184.desktop
[2022.11.24 18:02:53] Connecting local socket to /tmp/3f3c9fb8e36e9939b4c428f7f4a155a1-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
[2022.11.24 18:02:53] Socket connect error 0, starting server and app...
[2022.11.24 18:02:53] Moved logging from '/home/roman/.local/share/TelegramDesktop/log_start0.txt' to '/home/roman/.local/share/TelegramDesktop/log.txt'!
[2022.11.24 18:02:53] Opened '/home/roman/.local/share/TelegramDesktop/tdata/working' for reading, the previous Telegram Desktop launch was not finished properly :( Crash log size: 467
[2022.11.24 18:02:53] Font: from ':/gui/fonts/DAOpenSansRegular.ttf' loaded 'DAOpenSansRegular'
[2022.11.24 18:02:53] Font: from ':/gui/fonts/DAVazirRegular.ttf' loaded 'DAVazirRegular'
[2022.11.24 18:02:53] Font: from ':/gui/fonts/DAOpenSansRegularItalic.ttf' loaded 'DAOpenSansRegularItalic'
[2022.11.24 18:02:53] Font: from ':/gui/fonts/DAVazirRegular.ttf' loaded 'DAVazirRegular'
[2022.11.24 18:02:53] Font: from ':/gui/fonts/DAOpenSansSemiboldAsBold.ttf' loaded 'DAOpenSansSemibold'
[2022.11.24 18:02:53] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
[2022.11.24 18:02:53] Font: from ':/gui/fonts/DAOpenSansSemiboldItalicAsBold.ttf' loaded 'DAOpenSansSemiboldItalic'
[2022.11.24 18:02:53] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
[2022.11.24 18:02:53] Font: from ':/gui/fonts/DAOpenSansSemiboldAsBold.ttf' loaded 'DAOpenSansSemibold'
[2022.11.24 18:02:53] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
[2022.11.24 18:02:53] Font: from ':/gui/fonts/DAOpenSansSemiboldItalicAsBold.ttf' loaded 'DAOpenSansSemiboldItalic'
[2022.11.24 18:02:53] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
[2022.11.24 18:02:54] Update Info: MTP is unavailable.
[2022.11.24 18:02:54] App Error: _basePath is empty in writeSettings()
[2022.11.24 18:02:57] Primary screen DPI: 96
[2022.11.24 18:02:57] Found non-trivial Device Pixel Ratio: 2
[2022.11.24 18:02:57] Environmental variables: QT_DEVICE_PIXEL_RATIO=''
[2022.11.24 18:02:57] Environmental variables: QT_SCALE_FACTOR=''
[2022.11.24 18:02:57] Environmental variables: QT_AUTO_SCREEN_SCALE_FACTOR=''
[2022.11.24 18:02:57] Environmental variables: QT_SCREEN_SCALE_FACTORS=''
[2022.11.24 18:02:57] System tray available: [FALSE]
[2022.11.24 18:02:57] Icon theme: Adwaita
[2022.11.24 18:02:57] Fallback icon theme: 
[2022.11.24 18:02:57] App Info: reading settings...
[2022.11.24 18:02:57] App Info: reading encrypted settings...
[2022.11.24 18:02:57] Lang Info: Loaded cached, keys: 4272
[2022.11.24 18:02:57] OpenAL Logging Level: (not set)
[2022.11.24 18:02:57] Audio Playback Devices: Alder Lake PCH-P High Definition Audio Controller Speaker + Headphones;Alder Lake PCH-P High Definition Audio Controller HDMI / DisplayPort 3 Output;Alder Lake PCH-P High Definition Audio Controller HDMI / DisplayPort 2 Output;Alder Lake PCH-P High Definition Audio Controller HDMI / DisplayPort 1 Output
[2022.11.24 18:02:57] Audio Playback Default Device: Alder Lake PCH-P High Definition Audio Controller Speaker + Headphones
[2022.11.24 18:02:57] Audio Capture Devices: Alder Lake PCH-P High Definition Audio Controller Digital Microphone;Monitor of Alder Lake PCH-P High Definition Audio Controller HDMI / DisplayPort 3 Output;Monitor of Alder Lake PCH-P High Definition Audio Controller HDMI / DisplayPort 2 Output;Monitor of Alder Lake PCH-P High Definition Audio Controller HDMI / DisplayPort 1 Output;Monitor of Alder Lake PCH-P High Definition Audio Controller Speaker + Headphones;Alder Lake PCH-P High Definition Audio Controller Headphones Stereo Microphone
[2022.11.24 18:02:57] Audio Capture Default Device: Alder Lake PCH-P High Definition Audio Controller Digital Microphone
[2022.11.24 18:02:57] Not using Unity launcher counter.
[2022.11.24 18:02:57] App Info: reading accounts info...
[2022.11.24 18:02:57] App Info: reading encrypted info...
[2022.11.24 18:02:57] App Info: reading map...
[2022.11.24 18:02:57] App Info: reading encrypted map...
[2022.11.24 18:02:57] App Info: reading encrypted user settings...
[2022.11.24 18:02:57] App Info: encrypted user settings read.
[2022.11.24 18:02:57] App Info: reading encrypted mtp data...
[2022.11.24 18:02:57] MTP Info: read keys, current: 4, to destroy: 0
[2022.11.24 18:02:57] Map read time: 0
[2022.11.24 18:02:57] App Info: reading encrypted mtp config...
[2022.11.24 18:02:57] Export Info: Destroy top bar by controller removal.
[2022.11.24 18:02:57] OpenGL Profile: Compatibility.
[2022.11.24 18:02:57] OpenGL Renderer: Mesa Intel(R) Graphics (ADL GT2)
[2022.11.24 18:02:57] OpenGL Vendor: Intel
[2022.11.24 18:02:57] OpenGL Version: 4.6 (Compatibility Profile) Mesa 22.2.3
[2022.11.24 18:02:57] OpenGL Extensions: GL_EXT_texture_sRGB_R8, GL_EXT_polygon_offset_clamp, GL_ARB_ES3_compatibility, GL_EXT_framebuffer_sRGB, GL_ARB_transform_feedback_overflow_query, GL_SGIS_texture_edge_clamp, GL_ARB_texture_swizzle, GL_AMD_vertex_shader_layer, GL_ARB_multitexture, GL_ARB_invalidate_subdata, GL_ANGLE_texture_compression_dxt5, GL_AMD_pinned_memory, GL_ARB_vertex_buffer_object, GL_ARB_post_depth_coverage, GL_ARB_uniform_buffer_object, GL_ARB_clip_control, GL_ARB_enhanced_layouts, GL_NV_packed_depth_stencil, GL_ARB_vertex_attrib_binding, GL_EXT_packed_depth_stencil, GL_EXT_texture_snorm, GL_EXT_memory_object_fd, GL_EXT_depth_bounds_test, GL_EXT_compiled_vertex_array, GL_ARB_texture_buffer_object, GL_ARB_shading_language_include, GL_ARB_shadow, GL_ARB_draw_buffers, GL_ARB_fragment_program_shadow, GL_ARB_explicit_uniform_location, GL_3DFX_texture_compression_FXT1, GL_EXT_subtexture, GL_EXT_framebuffer_blit, GL_ARB_explicit_attrib_location, GL_EXT_texture_swizzle, GL_ARB_shader_atomic_counter_ops, GL_EXT_blend_color, GL_ARB_fragment_layer_viewport, GL_ARB_vertex_attrib_64bit, GL_ARB_shader_image_size, GL_EXT_semaphore, GL_ARB_gpu_shader5, GL_ARB_tessellation_shader, GL_EXT_point_parameters, GL_ARB_texture_non_power_of_two, GL_ARB_texture_query_levels, GL_KHR_blend_equation_advanced_coherent, GL_ARB_indirect_parameters, GL_EXT_shader_framebuffer_fetch_non_coherent, GL_EXT_texture_sRGB_decode, GL_ARB_seamless_cubemap_per_texture, GL_ARB_instanced_arrays, GL_EXT_texture_compression_dxt1, GL_ANGLE_texture_compression_dxt3, GL_EXT_abgr, GL_AMD_query_buffer_object, GL_ARB_compute_variable_group_size, GL_ARB_blend_func_extended, GL_ARB_vertex_array_bgra, GL_KHR_blend_equation_advanced, GL_ARB_texture_storage, GL_INTEL_shader_atomic_float_minmax, GL_SUN_multi_draw_arrays, GL_ARB_seamless_cube_map, GL_EXT_blend_equation_separate, GL_ARB_texture_query_lod, GL_ARB_texture_rgb10_a2ui, GL_ATI_texture_float, GL_ARB_compute_shader, GL_ARB_texture_env_dot3, GL_INTEL_blackhole_render, GL_EXT_texture_cube_map, GL_APPLE_packed_pixels, GL_ARB_gpu_shader_fp64, GL_ARB_conservative_depth, GL_ARB_buffer_storage, GL_ARB_point_sprite, GL_ARB_framebuffer_sRGB, GL_ARB_texture_stencil8, GL_INTEL_performance_query, GL_EXT_texture_env_dot3, GL_AMD_seamless_cubemap_per_texture, GL_ARB_shader_ballot, GL_INTEL_shader_integer_functions2, GL_ATI_fragment_shader, GL_ARB_shader_objects, GL_ARB_polygon_offset_clamp, GL_ARB_compressed_texture_pixel_storage, GL_ARB_sample_shading, GL_EXT_shadow_funcs, GL_ARB_cull_distance, GL_ARB_map_buffer_alignment, GL_ARB_texture_env_add, GL_ARB_fragment_shader_interlock, GL_EXT_blend_subtract, GL_ARB_shader_precision, GL_SGIS_generate_mipmap, GL_ARB_multi_draw_indirect, GL_EXT_packed_float, GL_ARB_shader_texture_lod, GL_ARB_shading_language_packing, GL_ARB_vertex_program, GL_ARB_gl_spirv, GL_EXT_shader_framebuffer_fetch, GL_EXT_texture_env_add, GL_ARB_transform_feedback2, GL_ARB_shader_subroutine, GL_ARB_stencil_texturing, GL_ARB_half_float_pixel, GL_ARB_occlusion_query, GL_EXT_draw_range_elements, GL_ARB_texture_mirrored_repeat, GL_ARB_texture_multisample, GL_EXT_EGL_image_storage, GL_AMD_draw_buffers_blend, GL_ARB_ES3_2_compatibility, GL_ARB_copy_buffer, GL_S3_s3tc, GL_SGIS_texture_lod, GL_KHR_texture_compression_astc_sliced_3d, GL_ARB_texture_compression_rgtc, GL_NV_copy_image, GL_ARB_texture_compression, GL_ARB_compatibility, GL_AMD_shader_trinary_minmax, GL_ARB_robust_buffer_access_behavior, GL_ARB_gpu_shader_int64, GL_ARB_texture_filter_anisotropic, GL_EXT_texture_compression_s3tc, GL_ARB_get_texture_sub_image, GL_KHR_parallel_shader_compile, GL_ATI_texture_env_combine3, GL_EXT_rescale_normal, GL_AMD_texture_texture4, GL_ARB_timer_query, GL_EXT_blend_minmax, GL_ARB_multisample, GL_ARB_texture_border_clamp, GL_ARB_texture_buffer_range, GL_EXT_EGL_sync, GL_ARB_depth_texture, GL_ARB_draw_elements_base_vertex, GL_MESA_texture_signed_rgba, GL_MESA_shader_integer_functions, GL_EXT_stencil_two_side, GL_ARB_texture_rg, GL_ARB_draw_buffers_blend, GL_ARB_shader_draw_parameters, GL_EXT_multi_draw_arrays, GL_OES_EGL_image, GL_ARB_window_pos, GL_ARB_clear_texture, GL_ARB_program_interface_query, GL_AMD_depth_clamp_separate, GL_ARB_copy_image, GL_NV_compute_shader_derivatives, GL_EXT_blend_func_separate, GL_EXT_texture_shared_exponent, GL_ARB_sync, GL_EXT_texture3D, GL_AMD_vertex_shader_viewport_index, GL_ARB_shader_stencil_export, GL_ARB_shader_viewport_layer_array, GL_ARB_conditional_render_inverted, GL_ARB_texture_compression_bptc, GL_EXT_texture_shadow_lod, GL_ATI_blend_equation_separate, GL_NV_light_max_exponent, GL_AMD_multi_draw_indirect, GL_NV_texture_barrier, GL_EXT_copy_texture, GL_ARB_shading_language_100, GL_ARB_vertex_type_2_10_10_10_rev, GL_EXT_vertex_array_bgra, GL_ARB_shader_group_vote, GL_EXT_provoking_vertex, GL_ARB_spirv_extensions, GL_EXT_texture_lod_bias, GL_EXT_draw_buffers2, GL_NV_primitive_restart, GL_ARB_occlusion_query2, GL_ARB_depth_clamp, GL_EXT_shader_integer_mix, GL_KHR_robustness, GL_ARB_texture_cube_map, GL_ARB_get_program_binary, GL_ARB_shading_language_420pack, GL_ARB_texture_float, GL_OES_read_format, GL_EXT_texture_array, GL_ARB_provoking_vertex, GL_ARB_draw_indirect, GL_ARB_transform_feedback3, GL_MESA_framebuffer_flip_y, GL_EXT_separate_specular_color, GL_ARB_vertex_array_object, GL_ARB_fragment_shader, GL_ARB_pipeline_statistics_query, GL_EXT_texture_object, GL_ARB_parallel_shader_compile, GL_INGR_blend_func_separate, GL_ARB_texture_cube_map_array, GL_ARB_robustness, GL_ARB_texture_env_crossbar, GL_ARB_multi_bind, GL_EXT_draw_instanced, GL_ARB_direct_state_access, GL_ARB_shader_texture_image_samples, GL_KHR_texture_compression_astc_ldr, GL_KHR_no_error, GL_ARB_fragment_program, GL_EXT_texture, GL_SGIS_texture_border_clamp, GL_ARB_clear_buffer_object, GL_MESA_pack_invert, GL_ARB_texture_storage_multisample, GL_ARB_ES3_1_compatibility, GL_ARB_internalformat_query2, GL_ARB_map_buffer_range, GL_EXT_pixel_buffer_object, GL_EXT_texture_sRGB, GL_IBM_multimode_draw_arrays, GL_NV_fog_distance, GL_EXT_memory_object, GL_EXT_stencil_wrap, GL_ARB_color_buffer_float, GL_ARB_texture_view, GL_EXT_framebuffer_object, GL_ARB_texture_mirror_clamp_to_edge, GL_AMD_conservative_depth, GL_KHR_robust_buffer_access_behavior, GL_EXT_gpu_shader4, GL_ARB_pixel_buffer_object, GL_EXT_texture_compression_rgtc, GL_ARB_vertex_type_10f_11f_11f_rev, GL_ARB_viewport_array, GL_EXT_texture_rectangle, GL_EXT_framebuffer_multisample_blit_scaled, GL_ARB_separate_shader_objects, GL_EXT_fog_coord, GL_ARB_texture_env_combine, GL_ARB_texture_buffer_object_rgb32, GL_EXT_transform_feedback, GL_ARB_query_buffer_object, GL_EXT_shader_samples_identical, GL_EXT_packed_pixels, GL_ARB_transform_feedback_instanced, GL_EXT_texture_edge_clamp, GL_ARB_texture_barrier, GL_EXT_texture_env_combine, GL_EXT_secondary_color, GL_ARB_half_float_vertex, GL_ARB_point_parameters, GL_ATI_separate_stencil, GL_NV_texgen_reflection, GL_IBM_rasterpos_clip, GL_KHR_context_flush_control, GL_MESA_window_pos, GL_ARB_arrays_of_arrays, GL_ARB_draw_instanced, GL_EXT_direct_state_access, GL_ARB_transpose_matrix, GL_ARB_depth_buffer_float, GL_KHR_debug, GL_EXT_framebuffer_multisample, GL_NV_texture_env_combine4, GL_AMD_shader_stencil_export, GL_ARB_debug_output, GL_ARB_shader_clock, GL_EXT_bgra, GL_ARB_vertex_shader, GL_EXT_texture_filter_anisotropic, GL_EXT_gpu_program_parameters, GL_EXT_semaphore_fd, GL_EXT_texture_integer, GL_EXT_vertex_attrib_64bit, GL_NV_depth_clamp, GL_ARB_shader_image_load_store, GL_NV_half_float, GL_ARB_fragment_coord_conventions, GL_ARB_derivative_control, GL_ARB_sampler_objects, GL_ATI_draw_buffers, GL_NV_conditional_render, GL_ARB_texture_rectangle, GL_EXT_texture_buffer_object, GL_ARB_shader_atomic_counters, GL_ARB_shader_bit_encoding, GL_NV_texture_rectangle, GL_EXT_demote_to_helper_invocation, GL_ARB_base_instance, GL_NV_fragment_shader_interlock, GL_EXT_vertex_array, GL_ARB_framebuffer_object, GL_ARB_framebuffer_no_attachments, GL_ARB_shader_storage_buffer_object, GL_NV_blend_square, GL_ARB_ES2_compatibility, GL_IBM_texture_mirrored_repeat, GL_ARB_texture_gather, GL_AMD_performance_monitor, GL_ARB_internalformat_query, GL_EXT_timer_query
[2022.11.24 18:02:57] OpenGL: QOpenGLContext created, version: 4.4.
[2022.11.24 18:02:57] OpenGL: [TRUE] (OverlayWidget)
[2022.11.24 18:02:57] Notification daemon product name: gnome-shell
[2022.11.24 18:02:57] Notification daemon vendor name: GNOME
[2022.11.24 18:02:57] Notification daemon version: 43.1
[2022.11.24 18:02:57] Notification daemon specification version: 1.2
[2022.11.24 18:02:57] Notification daemon capabilities: actions, body, body-markup, icon-static, persistence, sound
[2022.11.24 18:02:58] API Warning: not loaded minimal channel applied.
[2022.11.24 18:02:58] API Warning: not loaded minimal channel applied.
[2022.11.24 18:02:58] API Warning: not loaded minimal channel applied.
[2022.11.24 18:02:59] API Warning: not loaded minimal channel applied.
[2022.11.24 18:03:00] API Warning: not loaded minimal channel applied.
[2022.11.24 18:03:00] API Warning: not loaded minimal channel applied.
[2022.11.24 18:03:00] RPC Error: request 49 got fail with code 400, error WEBFILE_NOT_AVAILABLE
```

**Comment by jacob755** [comment]
this was crash on everything you set or even disabled
seems fixed in 4.3.3

**Comment by ilya-fedin** [comment]
It's a regression in mesa, you can see that by the fact the trace ends in your graphic drivers
https://gitlab.freedesktop.org/mesa/mesa/-/issues/7754

**Comment by MrSwed** [comment]
4.3.2, 4.3.3 - the problem is still there.  
downgrade to 4.3.1 helped

**Comment by ilya-fedin** [comment]
@MrSwed such reports were even before 4.3.3, you can see the linked mesa issues links some of them

**Comment by ilya-fedin** [comment]
It seems it's a Qt regression in fact, apparently Arch and flatpak just updated earlier than official binary, reverting https://github.com/qt/qtbase/commit/81252ea92ada20f97305278471c4fbb702213b9f fixes it
