### ISSUE TITLE
Win10 tablet mode: virtual keyboard not appearing when selecting text entry field

### ISSUE THREAD

**Issue by Gimrigz** [telegramdesktop/tdesktop#2562]
### Steps to reproduce
1.  Be in tablet mode on Win10
2. Click on the "write a message" field in any chat

### Expected behaviour
The windows virtual keyboard should appear automatically and the app should shrink so as to not have the keyboard hide the field.

### Actual behaviour
The windows virtual keyboard does not appear automatically upon clicking on the write message field.

### Configuration
**Operating system:**
Microsoft Surface Pro 4 on Windows 10 1604
**Version of Telegram Desktop:**
 0.10.16

### Note

You can call the virtual keyboard manually from the task bar. However, the Telegram app will not shrink and the keyboard will hide the "write message" field, as is the usual behavior.

**Comment by john-preston** [comment]
@Gimrigz It is a known Qt bug :(

https://bugreports.qt.io/browse/QTBUG-43190

**Comment by davidbaumann** [comment]
As this is the first result on Google and the QT bug has been fixed, but Telegram still shows that issue, I wanted to ask here.
Also I can't see what I am typing, as telegram window stays maximized even if I open the keyboard manually.

**Comment by john-preston** [comment]
@davidbaumann It was fixed in Qt 5.11 that was not released yet and which I can't yet use, because they've dropped a lot of system versions support :( It is also hard to backport to my Qt 5.6.2, because there is huge amount of code and changes.

**Comment by davidbaumann** [comment]
Thanks for the answer.
Also I think it's nice to have that mentioned here, might help others.
If you want me to test before release, just ask me.

**Comment by MarcusWolschon** [comment]
it is 2020 and this Bug still exists .
The input field still gets hidden .
