### ISSUE TITLE
Frequent crashes on Ubuntu 22.04

### ISSUE THREAD

**Issue by aguille** [telegramdesktop/tdesktop#26378]
### Steps to reproduce

Running the latest 64-bit static build on Ubuntu 22.04. The program segfaults every hour or so. Appears to be pretty random. A dump is generated. Sent crash report for one of them.

### Expected behaviour

No crashes.

### Actual behaviour

Segfault

### Operating system

Ubuntu 22.04. Gnome.

### Version of Telegram Desktop

4.8.3

### Installation source

Static binary from official website

### Crash ID

ef31efcc-fd18-4c90-151940bc-1c2fb435

**Comment by suprunchuk** [comment]
You can send an error report when you have such a window after the crash of the application. Your crash ID will be indicated there, attach it here

**Comment by aguille** [comment]
Crash ID: ef31efcc-fd18-4c90-151940bc-1c2fb435.

Should I keep sending crash reports whenever it happens ?

**Comment by suprunchuk** [comment]
_The crash ID should have been specified initially when creating this report. To do this, you have a separate line in the report._

When I used the snap version, I had crashes all the time. It was on both the stable and beta versions. I also created a bug report here, and I was advised to install the binary version from the official website. When I installed it, the crash of the application became much smaller, but they are still present. 
I have a stable crash of the application when opening a scheduled broadcast. For example, if you also have, you can [write there](https://github.com/telegramdesktop/tdesktop/issues/26374). But this will already be as a concrete example of a certain application crash.

**Comment by ilya-fedin** [comment]
@aguille What is the first version this started to happen on? It seem to crash on a semaphore in streamed file reader but this code had no changes for years.

**Comment by aguille** [comment]
@ilya-fedin It started to happen when I re-installed my workstation with Ubuntu 22.04. Before, I was using the snap package on Ubuntu 18.04 with no problem. After I upgraded (clean install), I started to get crashes with the snap package. So I switched to the static binary but the same problem is present. So the telegram version may be the same, but I guess a lot of other stuff has changed between 18.04 and 22.04.

**Comment by ilya-fedin** [comment]
Could it be that your computer hardware (e.g. RAM) has problems?

**Comment by aguille** [comment]
Given that it started when I made a software change, I'm inclined to think it's software-related. Besides, only Telegram is crashing. A hardware issue would affect everything pretty randomly. And I sent a few crash reports...isn't it always crashing at the same execution point ?

**Comment by Aokromes** [comment]
> Given that it started when I made a software change, I'm inclined to think it's software-related. Besides, only Telegram is crashing. A hardware issue would affect everything pretty randomly. And I sent a few crash reports...isn't it always crashing at the same execution point ?

well, the son of a friend had a lot of issues with one computer only with some games, at the end of all it was a faulty ram module that only crashed when ram use was very high.

**Comment by ilya-fedin** [comment]
> And I sent a few crash reports...

There's so much crash reports everyday, it's impossible to find yours ones without posting their IDs here...

**Comment by aguille** [comment]
They should all be tagged with my username. Here are some IDs:

221b0d11-9065-4e02-614093a8-5ebeb1f7
22b21981-5323-4ea5-98e1f597-dd02d9d4
4801e594-64e7-49cd-413645aa-f70d96ef
539c7f6f-a05e-406c-2aae77b6-7d8fcee6
5e9c3f9c-9feb-48ff-4a0c798f-b24089b4
79e774fc-3366-4ad7-63f6fa85-83624346
84447946-6cf4-4da7-0bfaaaab-cc19a3c9
c5bc23c4-3eb9-4c32-cfaba58d-a75c029b

**Comment by ilya-fedin** [comment]
@john-preston says the first 3 ones and the last 3 ones are not present on the server, apparently you forgot to send them. 4 and 5 are the same.

**Comment by yanovich** [comment]
There are hard to reproduce crashes on Ubuntu after an upgrade to 6.8 snap package. The crashes occur when an external link is clicked, but not 100% of time.

**Comment by Aokromes** [comment]
> There are hard to reproduce crashes on Ubuntu after an upgrade to 4.8 snap package. The crashes occur when an external link is clicked, but not 100% of time.
> 
> Edit: fixed version

clicking link crash was fixed on 4.8.4

**Comment by aguille** [comment]
> you can compress directory and send to t.me/preston if the file size is largest than 0 :)

Done !

**Comment by aguille** [comment]
Still happening with latest version:
Crash ID: 4c94e0ba-b290-4be4-bfd67ca6-9890e4d6

**Comment by aguille** [comment]
Crash ID: 56bcde72-599c-430c-9dbb9f87-d6b1353c

**Comment by ilya-fedin** [comment]
I guess all the reports are the same and reporting more won't help...

**Comment by aguille** [comment]
Alright then. I guess I just have to live with it...

**Comment by ilya-fedin** [comment]
You can try other builds (flatpak, snap), maybe it's a problem with the compiler. The code the trace points to hasn't seen a change for a long time but compiler options has.

**Comment by aguille** [comment]
I have the same problem with the snap package.

**Comment by ilya-fedin** [comment]
Do you have Intel iGPU? If yes, try to disable OpenGL.

**Comment by aguille** [comment]
My impression is that it crashes only when downloading/saving multiple files at once. It really seems related to file operations, not graphics. Now when I download I do one file at a time and I don't have crashes.

**Comment by ilya-fedin** [comment]
I suspect Intel drivers can produce memory corruption and corrupt the memory where the semaphore resides. There are very suspicious issues #26366, #26393.

**Comment by ilya-fedin** [comment]
> I have the same problem with the snap package.

Can you try the flatpak? It has a different optimization level.

**Comment by ilya-fedin** [comment]
ping?

**Comment by aguille** [comment]
Still hapenning but manageable if I only save one file at a time. I can live with that.
