### ISSUE TITLE
Closing separated chat window after closing the main window causes main window to reappear

### ISSUE THREAD

**Issue by xypha** [telegramdesktop/tdesktop#27656]
### Steps to reproduce

1. Quit Telegram (if already running).
2. Launch Telegram desktop (Windows 64 bit: **Portable**) on Windows 11.
3. `Ctrl + Left Click` on '**Saved Messages**' chat to open it in a new chat window.

![2024-03-15 @ 18：51：15](https://github.com/telegramdesktop/tdesktop/assets/12472214/41faf7ec-c2c4-4778-9b54-faff4f47759b)

4. Close 'Main window' by clicking on the 'Close' button in the title bar.
5. Close '**Saved Messages**' chat window by clicking on the 'Close' button in the title bar.
6. Bug is seen.

### Expected behaviour

Both main window and '**Saved Messages**' chat window remain closed.

### Actual behaviour

'Saved Messages' chat window remains closed, but  
Main window reappears on desktop.

### Operating system

Windows 11 Home Single Language 25H2 (OS Build 26200.9168)
 (last updated on 2026.09.04)

### Version of Telegram Desktop

v7.1.4 (last updated on 2026.09.04)
v6.6.2 (last updated on 2026.03.06)
v6.1.2 (last updated on 2025.09.06)
v5.5.1 (last updated on 2024.09.09)
v4.15.2 (originally reported on 2024.03.28 [yyyy.mm.dd])

### Installation source

Static binary from official website, followed by in-app updates

### Logs

```shell
[2024.03.28 00:46:23] Launched version: 4015002, install beta: [FALSE], alpha: 0, debug mode: [FALSE]
[2024.03.28 00:46:23] Executable dir: <redacted>/Telegram/, name: Telegram.exe
[2024.03.28 00:46:23] Initial working dir: <redacted>/Telegram/
[2024.03.28 00:46:23] Working dir: <redacted>/Telegram/
[2024.03.28 00:46:23] Command line: <redacted>\Telegram\Telegram.exe
[2024.03.28 00:46:23] Executable path before check: <redacted>/Telegram/Telegram.exe
[2024.03.28 00:46:23] Logs started
[2024.03.28 00:46:23] AppUserModelID: Telegram.TelegramDesktop.54e5a01c602f319902398f9d87dc0dc1
[2024.03.28 00:46:23] Connecting local socket to Global\dc76175af8c69268e651cbc1d81bdc10-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
[2024.03.28 00:46:23] This is the only instance of Telegram, starting server and app...
[2024.03.28 00:46:23] Moved logging from '<redacted>/Telegram/log_start0.txt' to '<redacted>/Telegram/log.txt'!
[2024.03.28 00:46:23] Global devicePixelRatio: 1
[2024.03.28 00:46:23] QT_DPI_ADJUSTMENT_POLICY: AdjustDpi
[2024.03.28 00:46:23] Primary screen DPI: 120, Base: 96.
[2024.03.28 00:46:23] Computed screen scale: 125
[2024.03.28 00:46:23] DevicePixelRatio: 1
[2024.03.28 00:46:23] ScreenScale: 125
[2024.03.28 00:46:23] Media Info: <redacted>
[2024.03.28 00:46:23] Media Info: <redacted>
[2024.03.28 00:46:23] Media Info: <redacted>
[2024.03.28 00:46:23] Font: from ':/gui/fonts/DAOpenSansRegular.ttf' loaded 'DAOpenSansRegular'
[2024.03.28 00:46:23] Font: from ':/gui/fonts/DAVazirRegular.ttf' loaded 'DAVazirRegular'
[2024.03.28 00:46:23] Font: from ':/gui/fonts/DAOpenSansRegularItalic.ttf' loaded 'DAOpenSansRegularItalic'
[2024.03.28 00:46:23] Font: from ':/gui/fonts/DAVazirRegular.ttf' loaded 'DAVazirRegular'
[2024.03.28 00:46:25] Font: from ':/gui/fonts/DAOpenSansSemiboldAsBold.ttf' loaded 'DAOpenSansSemibold'
[2024.03.28 00:46:25] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
[2024.03.28 00:46:25] Font: from ':/gui/fonts/DAOpenSansSemiboldItalicAsBold.ttf' loaded 'DAOpenSansSemiboldItalic'
[2024.03.28 00:46:25] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
[2024.03.28 00:46:25] Font: from ':/gui/fonts/DAOpenSansSemiboldAsBold.ttf' loaded 'DAOpenSansSemibold'
[2024.03.28 00:46:25] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
[2024.03.28 00:46:25] Font: from ':/gui/fonts/DAOpenSansSemiboldItalicAsBold.ttf' loaded 'DAOpenSansSemiboldItalic'
[2024.03.28 00:46:25] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
[2024.03.28 00:46:25] Using DirectX compiler '<redacted>\Telegram\modules\x86\d3d\d3dcompiler_47.dll'.
[2024.03.28 00:46:25] App Info: reading settings...
[2024.03.28 00:46:25] App Info: reading encrypted settings...
[2024.03.28 00:46:25] Lang Info: Loaded cached, keys: 6387
[2024.03.28 00:46:26] OpenAL Logging Level: (not set)
[2024.03.28 00:46:26] App Info: reading accounts info...
[2024.03.28 00:46:26] App Info: reading encrypted info...
[2024.03.28 00:46:26] App Info: reading map...
[2024.03.28 00:46:26] App Info: reading encrypted map...
[2024.03.28 00:46:26] App Info: reading encrypted user settings...
[2024.03.28 00:46:26] App Info: encrypted user settings read.
[2024.03.28 00:46:26] App Info: reading encrypted mtp data...
[2024.03.28 00:46:26] MTP Info: read keys, current: 5, to destroy: 0
[2024.03.28 00:46:26] Map read time: 131
[2024.03.28 00:46:26] App Info: reading encrypted mtp config...
[2024.03.28 00:46:26] Export Info: Destroy top bar by controller removal.
[2024.03.28 00:46:27] OpenGL: Using custom 'gpu_driver_bug_list.json'.
[2024.03.28 00:46:27] OpenGL Profile: OpenGLES.
[2024.03.28 00:46:27] OpenGL Renderer: ANGLE (Intel, Intel(R) UHD Graphics 605 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.101.1960)
[2024.03.28 00:46:27] OpenGL Vendor: Google Inc. (Intel)
[2024.03.28 00:46:27] OpenGL Version: OpenGL ES 3.0.0 (ANGLE 2.1.10 git hash: e3f59e8d0c3e)
[2024.03.28 00:46:27] OpenGL Extensions: GL_EXT_multi_draw_indirect, GL_AMD_performance_monitor, GL_OES_mapbuffer, GL_ANGLE_texture_usage, GL_CHROMIUM_bind_uniform_location, GL_EXT_draw_buffers_indexed, GL_OES_EGL_image_external_essl3, GL_EXT_robustness, GL_OES_compressed_ETC2_sRGB8_texture, GL_EXT_texture_format_BGRA8888, GL_EXT_texture_rg, GL_OES_texture_half_float_linear, GL_EXT_clip_cull_distance, GL_EXT_sRGB, GL_EXT_texture_compression_dxt1, GL_EXT_texture_compression_rgtc, GL_OES_texture_float_linear, GL_OES_compressed_EAC_R11_signed_texture, GL_ANGLE_multiview_multisample, GL_EXT_multisampled_render_to_texture, GL_OES_compressed_ETC2_RGB8_texture, GL_OES_draw_buffers_indexed, GL_EXT_blend_minmax, GL_ANGLE_provoking_vertex, GL_EXT_depth_clamp, GL_OES_sample_variables, GL_OES_EGL_image, GL_EXT_texture_border_clamp, GL_EXT_disjoint_timer_query, GL_OES_compressed_EAC_RG11_signed_texture, GL_EXT_texture_type_2_10_10_10_REV, GL_ANGLE_request_extension, GL_EXT_polygon_offset_clamp, GL_NV_framebuffer_blit, GL_OES_EGL_image_external, GL_ANGLE_renderability_validation, GL_KHR_parallel_shader_compile, GL_OES_texture_stencil8, GL_EXT_occlusion_query_boolean, GL_EXT_texture_norm16, GL_CHROMIUM_copy_texture, GL_ANGLE_shader_pixel_local_storage, GL_OES_depth24, GL_NV_EGL_stream_consumer_external, GL_EXT_draw_buffers, GL_OES_texture_border_clamp, GL_KHR_debug, GL_ANGLE_get_serialized_context_string, GL_ANGLE_depth_texture, GL_CHROMIUM_copy_compressed_texture, GL_ANGLE_clip_cull_distance, GL_ANGLE_client_arrays, GL_EXT_color_buffer_half_float, GL_CHROMIUM_lose_context, GL_OES_texture_half_float, GL_EXT_map_buffer_range, GL_ANGLE_instanced_arrays, GL_EXT_base_instance, GL_EXT_clip_control, GL_OES_fbo_render_mipmap, GL_EXT_read_format_bgra, GL_ANGLE_framebuffer_multisample, GL_EXT_texture_compression_bptc, GL_APPLE_clip_distance, GL_CHROMIUM_bind_generates_resource, GL_ANGLE_get_tex_level_parameter, GL_EXT_frag_depth, GL_NV_fence, GL_NV_pack_subimage, GL_OES_surfaceless_context, GL_ANGLE_copy_texture_3d, GL_EXT_debug_label, GL_ANGLE_texture_multisample, GL_EXT_draw_elements_base_vertex, GL_EXT_texture_filter_anisotropic, GL_ANGLE_memory_size, GL_ANGLE_program_cache_control, GL_EXT_texture_compression_s3tc_srgb, GL_EXT_instanced_arrays, GL_EXT_float_blend, GL_EXT_EGL_image_external_wrap_modes, GL_EXT_texture_mirror_clamp_to_edge, GL_OVR_multiview2, GL_EXT_blend_func_extended, GL_CHROMIUM_sync_query, GL_EXT_texture_storage, GL_OES_element_index_uint, GL_OVR_multiview, GL_OES_compressed_EAC_R11_unsigned_texture, GL_OES_packed_depth_stencil, GL_ANGLE_framebuffer_blit, GL_ANGLE_pack_reverse_row_order, GL_ANGLE_shader_pixel_local_storage_coherent, GL_WEBGL_video_texture, GL_OES_standard_derivatives, GL_EXT_color_buffer_float, GL_OES_compressed_ETC2_punchthroughA_sRGB8_alpha_texture, GL_ANGLE_lossy_etc_decode, GL_OES_depth32, GL_ANGLE_base_vertex_base_instance, GL_ANGLE_base_vertex_base_instance_shader_builtin, GL_ANGLE_stencil_texturing, GL_ANGLE_texture_compression_dxt3, GL_OES_texture_npot, GL_EXT_shader_texture_lod, GL_OES_compressed_ETC2_sRGB8_alpha8_texture, GL_EXT_discard_framebuffer, GL_OES_compressed_EAC_RG11_unsigned_texture, GL_ANGLE_texture_compression_dxt5, GL_EXT_debug_marker, GL_OES_get_program_binary, GL_ANGLE_translated_shader_source, GL_EXT_conservative_depth, GL_EXT_render_snorm, GL_OES_compressed_ETC2_RGBA8_texture, GL_OES_vertex_array_object, GL_NV_shader_noperspective_interpolation, GL_OES_draw_elements_base_vertex, GL_ANGLE_polygon_mode, GL_ANGLE_robust_client_memory, GL_OES_shader_multisample_interpolation, GL_ANGLE_multi_draw, GL_OES_compressed_ETC2_punchthroughA_RGBA8_texture, , GL_EXT_unpack_subimage, GL_NV_pixel_buffer_object, GL_OES_rgb8_rgba8, GL_OES_texture_float
[2024.03.28 00:46:27] EGL Extensions: EGL_EXT_create_context_robustness, EGL_ANGLE_d3d_share_handle_client_buffer, EGL_ANGLE_d3d_texture_client_buffer, EGL_ANGLE_surface_d3d_texture_2d_share_handle, EGL_ANGLE_query_surface_pointer, EGL_ANGLE_window_fixed_size, EGL_ANGLE_keyed_mutex, EGL_ANGLE_surface_orientation, EGL_ANGLE_direct_composition, EGL_ANGLE_windows_ui_composition, EGL_NV_post_sub_buffer, EGL_KHR_create_context, EGL_KHR_image, EGL_KHR_image_base, EGL_KHR_gl_texture_2D_image, EGL_KHR_gl_texture_cubemap_image, EGL_KHR_gl_renderbuffer_image, EGL_KHR_get_all_proc_addresses, EGL_KHR_stream, EGL_KHR_stream_consumer_gltexture, EGL_NV_stream_consumer_gltexture_yuv, EGL_ANGLE_stream_producer_d3d_texture, EGL_ANGLE_create_context_webgl_compatibility, EGL_CHROMIUM_create_context_bind_generates_resource, EGL_CHROMIUM_sync_control, EGL_EXT_pixel_format_float, EGL_KHR_surfaceless_context, EGL_ANGLE_display_texture_share_group, EGL_ANGLE_display_semaphore_share_group, EGL_ANGLE_create_context_client_arrays, EGL_ANGLE_program_cache_control, EGL_ANGLE_robust_resource_initialization, EGL_ANGLE_create_context_extensions_enabled, EGL_ANDROID_blob_cache, EGL_ANDROID_recordable, EGL_ANGLE_image_d3d11_texture, EGL_ANGLE_create_context_backwards_compatible, EGL_KHR_no_config_context, EGL_KHR_create_context_no_error, EGL_KHR_reusable_sync, 
[2024.03.28 00:46:27] OpenGL: QOpenGLContext created, version: 3.3.
[2024.03.28 00:46:27] OpenGL: [TRUE] (Window)
[2024.03.28 00:46:29] API Warning: not loaded minimal channel applied.
[2024.03.28 00:46:29] API Warning: not loaded minimal channel applied.
[2024.03.28 00:46:29] API Warning: not loaded minimal channel applied.
[2024.03.28 00:46:30] API Warning: not loaded minimal channel applied.
[2024.03.28 00:46:31] RPC Error: request 103 got fail with code 400, error USER_NOT_PARTICIPANT
[2024.03.28 00:46:31] API Warning: not loaded minimal channel applied.
[2024.03.28 00:46:32] API Warning: not loaded minimal channel applied.
[2024.03.28 00:46:32] Export Info: Destroy top bar by controller removal.
```

**Comment by JackLiuyiyao** [comment]
can this be fixed by modifying the webview_embed.cpp? If not please ignore this comment

**Comment by xypha** [comment]
this bug still exists in v5.12.1

**Comment by xypha** [comment]
This bug still exists in Telegram desktop v6.1.2 and I am definitely interested in resolving it

**Comment by xypha** [comment]
This bug still exists in Telegram desktop v6.6.2 and I am definitely interested in resolving it

**Comment by xypha** [comment]
This bug still exists in Telegram desktop v7.1.4 and I am definitely interested in resolving it
