### ISSUE TITLE
Incorrect flatpak name

### ISSUE THREAD

**Issue by rivenirvana** [telegramdesktop/tdesktop#27712]
### Steps to reproduce

1. Install via `flatpak install flathub-beta org.telegram.desktop`.
2. Invoke `flatpak list` or `flatpak info org.telegram.desktop` and look for the application's name.

### Expected behaviour

The application's printed name should be "Telegram Desktop" or something similar.

### Actual behaviour

The command reports "John Preston" as the application name.

### Operating system

Fedora 40 Workstation Beta; GNOME 46; flatpak 1.15.6

### Version of Telegram Desktop

4.16.2 flathub-beta branch

### Installation source

Flatpak

**Comment by niranjansah87** [comment]
It is already fixed

**Comment by rivenirvana** [comment]
I waited for an update, which I just received earlier, before replying to this again. Version states 4.16.3~beta, the screenshot below shows the issue still present. `flatpak list` and `flatpak info` prints "John Preston".
![Screenshot from 2024-04-06 19-22-52](https://github.com/telegramdesktop/tdesktop/assets/43519644/795a9718-45fa-470a-b8f5-bc8f0524d658)

I don't think this is a problem on my end locally.

**Comment by rivenirvana** [comment]
Just updated to 4.16.4, this is still the case.

**Comment by ilya-fedin** [comment]
This honestly looks like flatpak infra bug to me... Nothing was changed in tdesktop regarding to application name. Unless you have an evidence that is a bug in tdesktop, I don't think this is the right place for this report (I don't know what would be the right place, though).
