### ISSUE TITLE
Telegram desktop doesnt run on arch: out of memory

### ISSUE THREAD

**Issue by dnaik42** [telegramdesktop/tdesktop#27752]
### Steps to reproduce

Go to installed directory and run `./Telegram`

### Expected behaviour

Launches the application

### Actual behaviour

Freezes and is killed by oom
```
Apr 14 17:46:32 yoga6dnaik kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/session-1.scope,task=Telegram,pid=20620,uid=1000
Apr 14 17:46:32 yoga6dnaik kernel: Out of memory: Killed process 20620 (Telegram) total-vm:68918224kB, anon-rss:13569660kB, file-rss:944kB, shmem-rss:0kB, UID:1000 pgtables:38820kB oom_score_adj:0
Apr 14 17:46:32 yoga6dnaik systemd[1]: session-1.scope: A process of this unit has been killed by the OOM killer.
```

### Operating system

Arch Linux

### Version of Telegram Desktop

4.16.6

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> Go to installed directory and run `./Telegram`

I'm unable to reproduce with just this step. Perhaps something is missing?

**Comment by dnaik42** [comment]
I get the same error even when running the telegram-desktop package

**Comment by ilya-fedin** [comment]
this package is made by third parties

**Comment by Lynnatos** [comment]
I made a fresh arch install and tested the Telegram from official website, from the repositories and they showed the same behavior, freezes the entire system. On gnome it manages to kill the telegam before telegram makes the system freeze entirely. So, i think that the problem is related with some dependency, a shared library shipped on arch, but i couldn't figure that out.

**Comment by ilya-fedin** [comment]
I can't reproduce on my VM... Maybe it's something hardware-dependent?

**Comment by Lynnatos** [comment]
i wouldn't be surprised at all if it was related with t he nvidia drivers, now that i think about it.

**Comment by dnaik42** [comment]
@Lynnatos I do not have an nvidia GPU, I am using integrated Intel graphics.

**Comment by luanlouzada** [comment]
I'm having the same problem

**Comment by younggggger** [comment]
mark

**Comment by oktiecodes** [comment]
Same thing happening on my machine, Arch too.
However starting from a TTY works just fine. (e.g. `DISPLAY=:0 telegram-desktop`)
~~Could it be an env issue?~~
Investigated further and here's the results:
Running with `env -i DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY HOME=$HOME telegram-desktop` works just fine.

**Comment by oktiecodes** [comment]
Investigating more i found out that i need to unset these: `KDE_FULL_SESSION` and `XDG_CURRENT_DESKTOP`, to make it work, no idea why this works.

**Comment by notrodans** [comment]
`unset QT_QPA_PLATFORMTHEME && telegram-desktop` working for me.

**Comment by aiuoe** [comment]
this issue is resolved 😀

**Comment by dnaik42** [comment]
`telegram-desktop` works after `unset QT_QPA_PLATFORMTHEME`, but the official binary still isn't working.

**Comment by asdcxfrt** [comment]
Encountered the identical error post-system upgrade. Observed that both myself and @luanlouzada are utilizing the theme from https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme. Switching to Adwaita theme resolved the issue of launching Telegram.

This insight could aid in replicating the problem. @Aokromes

**Comment by ilya-fedin** [comment]
I installed it through install.sh in the repo, tried both Tokyonight-Light and Tokyonight-Dark in Plasma GTK settings yet I can't reproduce

**Comment by asdcxfrt** [comment]
Have you installed the icon pack from this theme?
If it helps you, then I use Cinnamon.

**Comment by ilya-fedin** [comment]
> Have you installed the icon pack from this theme?

No, I haven't. Is this necessary?

> If it helps you, then I use Cinnamon.

On Arch?

**Comment by asdcxfrt** [comment]
Yeah. I use cinnamon on Arch.
I don't know what the error might be related to and thought all the system information might be helpful.

**Comment by asdcxfrt** [comment]
Yes. The problem was the icon theme.
Before that, I had disabled everything (including icons) that was related to Tokyo Night.
 
But as a result, I noticed that Telegram's performance depends on the icon theme selected. I don't know why.

**Comment by ilya-fedin** [comment]
I have a trouble applying the icon theme. The time I open the icons section in Plasma settings application, it gets affected by this bug...

**Comment by ilya-fedin** [comment]
I applied the icon theme somehow and now any Qt application gets killed by the OOM killer on my system...

**Comment by dnaik42** [comment]
Confirmed, the official binary works when using Adwaita icon pack.

**Comment by ilya-fedin** [comment]
This looks like a Qt bug to me, not a tdesktop bug...

**Comment by dnaik42** [comment]
All other QT Applications are working for me.

**Comment by ilya-fedin** [comment]
@dnaik42 maybe you just don't have icon theme configured for them? or maybe they aren't Qt6 applications?

**Comment by Aokromes** [comment]
> All other QT Applications are working for me.

try qbittorrent with qt6.

**Comment by asdcxfrt** [comment]
@Aokromes I tried running qBittorrent, and it worked perfectly, with this problematic icon theme.

**Comment by asdcxfrt** [comment]
@ilya-fedin
I have now uninstalled the version that I installed through the package manager and built a new version from source. The libraries that I used are:
Qt: 6.7.0,
Libtorrent: 2.0.10.0,
Boost: 1.83.0,
OpenSSL: 3.2.1,  
Zlib 1.3.1.

And it works successfully with the icons of this theme.

**Comment by ilya-fedin** [comment]
qbittorrent works, indeed. dolphin doesn't, though. idk what is the system but looks like it doesn't affect all Qt applications, yet tdesktop is not the only one affected on my system so I'm not convinced that's a tdesktop bug. I don't even imagine how that could be a tdesktop bug, honestly.

**Comment by oktiecodes** [comment]
> I applied the icon theme somehow and now any Qt application gets killed by the OOM killer on my system...

same thing is happening for me and i have no idea how to fix that

**Comment by ilya-fedin** [comment]
@oktiecodes in case of KDE, you can remove the parameter from `~/.config/kdeglobals`

**Comment by junx404** [comment]
I have the same problem on opensuse tumbleweed. Tried repo, official and flatpak, both on hyprland and gnome xorg

**Comment by SilverRisha** [comment]
> `unset QT_QPA_PLATFORMTHEME && telegram-desktop` working for me.

fixes the issue , even for the latest telegram package from official arch repo
thanks <3

**Comment by matinabbasi788** [comment]
> > `unset QT_QPA_PLATFORMTHEME && telegram-desktop` working for me.
> 
> fixes the issue , even for the latest telegram package from official arch repo thanks <3

its really work i cannot open my telegram for a month

**Comment by dnaik42** [comment]
Solved after upgradding to telegram-desktop 5.1.0
