### ISSUE TITLE
Crash when pressing the ESC key to exit the search while filtering "My Notes" on "Saved Messages"

### ISSUE THREAD

**Issue by eduhoribe** [telegramdesktop/tdesktop#27997]
### Steps to reproduce

1. Resize the window to the minimum possible size
2. Go to "Saved Messages"
3. Click on the top bar
4. Click on "My Notes"
5. Click on "magnifier" icon
6. Press the <kbd>ESC</kbd> key

### Expected behaviour

The app should go back to the "My Notes" screen

### Actual behaviour

The app crashes

### Operating system

Windows 10

### Version of Telegram Desktop

5.0.6 beta x64

### Installation source

Static binary from official website

### Crash ID

1b007e95-1804-4fb1-8e1b-e4dcf760a26d

**Comment by kasumiru** [comment]
Can't reproduce this. Windwos 11, TGdesktop 5.2.3 X64. 
The ESC button closes the search correctry.  
![image](https://github.com/user-attachments/assets/f17f766e-c59e-45c8-8b8c-d4556606d800)

**Comment by Aokromes** [comment]
maybe it was fixed since 5.0.6.

**Comment by eduhoribe** [comment]
Just tested again on 5.4.1 x64 and it still crashes.

The Crash ID is now `C7b4e3ae0-d074-4d9e-ad63-66aa4b2017ed`

It looks to me that you didn't click on the "My Notes" @kasumiru. It should look more like this before crashing:

![image](https://github.com/user-attachments/assets/3793b2dd-f6a4-4be4-b0d2-c038f4a76ecd)
