### ISSUE TITLE
Webview Crash when trying to add credit card for /gift subscription

### ISSUE THREAD

**Issue by gbcox** [telegramdesktop/tdesktop#28559]
### Steps to reproduce

1. Enter /gift in @PremiumBot
2. Select recipient 
3. Choose length of subscription
4. In checkout popup select: Payment Method
5. New Card popup appears with message: Error Webview Has Crashed

### Expected behaviour

You should be prompted to enter payment method, i.e. credit card number

### Actual behaviour

Receive message: Error: WebView has crashed.

### Operating system

Fedora 40, Plasma 6

### Version of Telegram Desktop

Version 5.6.3

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and send crash id on next start and post id here.

**Comment by gbcox** [comment]
> plz enable beta, restart telegram and send crash id on next start and post id here.

Thanks for the quick reply.  Telegram isn't crashing itself, it appears only webview - and as far as I can tell, no crash id is being generated.  I tried activating enable webview inspection, but when I right-click on the popup window nothing happens.  Beta was enabled.

**Comment by gbcox** [comment]
> What version of webkitgtk do you have? webkitgtk 2.46+ doesn't work with web bots on Wayland, see #25126

Ah, ok.  I have: webkitgtk6.0-2.46.1-1.fc40.x86_64

Thanks for the quick reply!

The workaround is to just use the iphone app or web app. So it isn't the end of the world, but hopefully it can eventually be resolved.  It's a bit annoying.  I use the desktop app all the time.

**Comment by ilya-fedin** [comment]
You can use flatpak or snap version that have webkitgtk or switch to x11 that operates with web bots with way less bugs in general.

**Comment by ilya-fedin** [comment]
No, they won't, because tdesktop embeds webkitgtk into Qt UI with QtWaylandCompositor library that is meant to make compositors for Qt commerical users such as automotive companies manufacturing head units. They run those compositors bare metal. While tdesktop uses this library to create a nested compositor for window embedding. As this use case is not typical for the library, it crashes on a second EGL construction. I reported it long time ago as https://bugreports.qt.io/browse/QTBUG-115063 but then Qt employer honestly said my use case is not well-supported (and they don't really care about that I guess as tdesktop isn't a commercial user). As a workaround for that, I disabled access to EGL for webkitgtk process. But then in 2.46 came https://bugs.webkit.org/show_bug.cgi?id=280239 (mentioned in #25126) and then the maintainer says in bug report "EGL has been mandatory for a while (and was always mandatory with Wayland)." which I read as it's not going to be fixed (with a reasonable deadline at least). It's not suprising given that when you don't have a graphics driver, you still have llvmpipe and EGL still works. It's solely tdesktop use-case that works around a Qt bug so I have no doubt those both issues aren't going to be fixed in a decade.

**Comment by gbcox** [comment]
Hey, good news!  With the latest updates the issue has been fixed.

**Comment by ilya-fedin** [comment]
That is only because Qt is now patched to prevent QTBUG-115063... I.e. all third-party builds using vanilla Qt will still crash. And longer term I believe Wayland compatibility will have to be removed anyway.

**Comment by gbcox** [comment]
I'm hopefull they'll work to get it all straightened out.  They're good people.

**Comment by ilya-fedin** [comment]
IDK who you're talk about. My experience contacting Qt people so far is that they don't care about use cases other than their paid clients and maybe KDE. tdesktop is neither of these. I haven't contacted WebKit/GTK people but those look like caring only about GTK/epiphany use cases.
