### ISSUE TITLE
Wrong video rotation upon uploading

### ISSUE THREAD

**Issue by AkvenJan** [telegramdesktop/tdesktop#30093]
### Steps to reproduce

I have a vertical video shot by Iphone. It had this propetries in MediaInfo
Width                       : 1 920 pixels
Height                      : 1 080 pixels
Display aspect ratio        : 16:9
Rotation                    : 90°

So it is landscape video with rotation flag. Telegram Desktop ignores Rotation flag upon uploading
Original video:

<img width="655" height="1354" alt="Image" src="https://github.com/user-attachments/assets/992cdeef-89f9-484d-bc9c-8a767e139095" />
Result in Telegram Desktop

<img width="974" height="500" alt="Image" src="https://github.com/user-attachments/assets/34871eb4-1834-4cc1-b6f4-5c44e7490e59" />
And the result is even worse in mobile version

<img width="650" height="1093" alt="Image" src="https://github.com/user-attachments/assets/0fefa1c7-7d30-4a58-b624-6df89ef1c1ce" />

But if I upload this video in mobile version - everything is ok

### Expected behaviour

Telegram Desktop must read Rotation flag from meta

### Actual behaviour

Video get wrongly rotated by Telegram Desktop upon uploading

### Operating system

Windows 11

### Version of Telegram Desktop

Telegram Desktop 6.3.6 x64

### Installation source

Static binary from official website

### Logs

```shell

```

**Comment by Aokromes** [comment]
so, this bug is fixed now? if yes, close.

**Comment by kr-ilya** [comment]
The video is playing correctly, but the preview (chat view) is not displayed correctly.
version 6.8.2

On android, the preview is displayed incorrectly, just like on the desktop. (horizontal for vertical video)

**Comment by nonme** [comment]
Bug is not fixed. Confirmed as of today since I was googling for ways to resolve this issue. Please add users an option to rotate video manually if they want, but don't do anything with them on your own. This is UI anti-pattern from your side.

**Comment by vibes24** [comment]
Desktop continues to mess up with my attachments. Please fix it.
