### ISSUE TITLE
Telegram Desktop input field is under onscreen keyboard on tablet in landscape orientation, so it's not visible to user

### ISSUE THREAD

**Issue by RussianNeuroMancer** [telegramdesktop/tdesktop#3274]
### Steps to reproduce
1. Install Linux with Gnome Shell and [Onboard](https://launchpad.net/onboard) on x86 tablet; deal with touchscreen driver, if there is any issue,
2. Configure Gnome Shell and Onboard by following recommendations below,
3. Set screen to landscape orientation if it's not default, start Telegram, select chat, summon Onboard.

### Expected behaviour
Onboard appear on the screen, input field is visible

### Actual behaviour
Onboard interfere with Telegram's [windowMinHeight](https://github.com/telegramdesktop/tdesktop/blob/22d905b39c6d0f535748043c11c0da9b19c388a1/Telegram/SourceFiles/window/window.style#L27), therefore input field turn out to be under Onboard, so user can't see text that he enter. Qt seems like take font size from "Gnome Tweak Tool" as recommendation for DPI calculation, so issue is reproducible even if there is enough space for Telegram window (480 or more pixels is available.)

### Configuration
**Environment:**
Ubuntu Gnome 16.04, 16.10 and 17.04 was tested
Lenovo Thinkpad Helix, Dell 5855, Dell 7140, Dell 9250, DEXP Ursus 7W, DEXP Ursus 10XW tablets was tested
Screen resolution from 1024x600 to 1920x1080 was tested
Onscreen keyboard Onboard has been used instead of Caribou (Gnome Shell integrated onscreen keyboard) because there is no Russian keyboard layout in Caribou
Telegram version is 1.0.29, default theme.

**Gnome Tweak Tool settings:**
Font size was set to 1.15-1.5 depends on the screen size and screen resolution. This is important to adjust this option to some sane value to reproduce this issue. For example for 1920x1080 set Font size to 1.30.

**Onboard settings**:
Onboard was configured to be attached the bottom edge of the screen
Onboard size was set to around 40% of the screen in landscape orientation

**Comment by Aokromes** [comment]
#1297 ?

**Comment by RussianNeuroMancer** [comment]
Different issue, I think. In my case window get resized, but not below windowMinHeight.

**Comment by RussianNeuroMancer** [comment]
Still reproducible, so please keep it open.

**Comment by ell1e** [comment]
Sorry for making the duplicate issue #8058 here, but to sum it up: this is also an issue with the PinePhone, and possibly the upcoming Librem 5, Vollafone, and other mobile phones that might run Linux in the future (with systems like Ubuntu Touch, Phosh, or Plasma Mobile)

**Comment by ell1e** [comment]
This is definitely still a problem, and not resolved.

**Comment by ell1e** [comment]
Still broken.

**Comment by proycon** [comment]
I see this issue has popped up in several tickets already (#8058, #16368), most of them got closed without an actual solution and with the note that tdesktop wasn't designed for phones/tablets or small screens. I of course respect that  the focus is on desktops, but I want to emphasize that in [Sxmo](https://sxmo.org) (a UI for linux phones like the pinephone), tdesktop really works almost perfectly under Xorg (with dwm as window manager), despite the small screen. I say this to:

1) Request that tdesktop is not completely discarded as a viable solution for linux phones. The experience on Sxmo shows that tdesktop works quite well in general, also in combination with the virtual keyboard and the limited screen estate.
2) Inform that this issue seems wayland specific (and possibly specific to wlr-layer-shell). We're currently developing a wayland version of Sxmo, using sway as compositor, and we can replicate the exact same issue there; the text input field is missing there; and this can also be replicated on a desktop system with a virtual keyboard.
3) As this issue indicates, it's not limited to mobile devices, I can also replicate it on laptop/desktop with sway with a slightly oversized virtual keyboard. I used our fork of [wvkbd](https://github.com/proycon/wvkbd/), where the height of the keyboard is configurable through a parameter, which it useful for good testing this bug.

I attach of screenshot of tdesktop working **well** on sxmo (X11, dwm) on a pinephone:

![sxmo_telegram](https://user-images.githubusercontent.com/75427/136673397-bd4a22fb-a159-4c73-9bfc-2e04e86543c5.png)

**Comment by ilya-fedin** [comment]
It's unlikely tdesktop will be ever adapted to linux phones by efforts of their team. If you want better support for linux phones (or tablets, transformers, etc, yeah), the only way is to create PRs. You can ask @john-preston which changes in widgets are needed to decrease minimal window height.

**Comment by ell1e** [comment]
:weary:

**Comment by gurucubano** [comment]
I have a similar issue with one of my Linux mobile phone Purism L5. The one which works fine runs `telegram-desktop` 3.7.3, the other runs 4.1.1 and there the OSK overlaps the input widget when the OSK is brought up. The problem seems to be that in 4.1.1 the list of older messages in the chat is not shifted upwards enough. See attached screen (two of the correct working 3.7.7m the last of the broken one):

![tg373-2022-11-14-124602](https://user-images.githubusercontent.com/8157672/202642157-845a73fe-a7f6-4d46-aa4a-a87ff1a0f50e.jpg)
![tg373-2022-11-14-124637](https://user-images.githubusercontent.com/8157672/202642151-39070930-8f4c-4e96-8a97-e53bb1326214.jpg)

broken:
![tg411-2022-11-18-074830](https://user-images.githubusercontent.com/8157672/202642525-1b568e59-8210-4f0b-b395-1dbc7c11d502.jpg)

**Comment by gurucubano** [comment]
Hello  @john-preston could you please point me to the location where to change this problem. Thanks

**Comment by ilya-fedin** [comment]
@john-preston sadly doesn't seem interested in resolving this problem. Another way to fix the problem is probably adjusting input fields to [QInputMethod::keyboardRectangle](https://doc.qt.io/qt-5/qinputmethod.html#keyboardRectangle-prop). QInputMethod instance can be gotten with [QGuiApplication::inputMethod](https://doc.qt.io/qt-5/qguiapplication.html#inputMethod). This should be an easier way to fix this as this doesn't require changing window limits and so working together with Telegram designers, but sadly personally I can't work on this as I don't have any device to reproduce this. But I think I'll be able to help anyone interested to implement this with QInputMethod.

**Comment by gurucubano** [comment]
El día Dienstag, Dezember 06, 2022 a las 11:52:05 -0800, ilya-fedin escribió:

> @john-preston sadly doesn't seem interested in resolving this problem. Another way to fix the problem is probably adjusting input fields to [QInputMethod::keyboardRectangle](https://doc.qt.io/qt-5/qinputmethod.html#keyboardRectangle-prop). QInputMethod instance can be gotten with [QGuiApplication::inputMethod](https://doc.qt.io/qt-5/qguiapplication.html#inputMethod). This should be an easier way to fix this as this doesn't require changing window limits and so working together with Telegram designers, but sadly personally I can't work on this as I don't have any device to reproduce this. But I think I'll be able to help anyone interested to implement this with QInputMethod.
> 

If some could produce a flatpak pkg for the Purism L5 (Debian), I could
give it a try. Actually, I can't compile from sources.

-- 
Matthias Apitz, ✉ ***@***.***, http://www.unixarea.de/ +49-176-38902045
Public GnuPG key: http://www.unixarea.de/key.pub

**Comment by ilya-fedin** [comment]
The thing is someone having appropriate device and/or interest has to compile from sources and do the development

**Comment by chloe-everhart** [comment]
Still broken:
I use Pop! OS with 200% scaling and the Night Color always turned up most of the way. Telegram is installed as Flatpak through Pop! Shop.

My accessibility options broke the Telegram UI. Using 200% scaling from the GNOME settings menu, the area where I type the messages is off the screen, and I can't shrink the window so it will fit on the screen. I can't get to all the menu options.

When I click the thoughtfully placed icon to switch to 100%, everything gets too small to read easily, but the buttons are back on the page. When I turn off "use system defaults", and use the slider to increase the scale to where reading it is comfortable, the type box and menu options are off the page and inaccessible again.

Could you please help me find a solution, so that Telegram won't get bigger than my monitor when I scale to 250% or 300%?"

**Comment by ilya-fedin** [comment]
@chloe-everhart there's sadly no solution as tdesktop is just not designed for such small window sizes

**Comment by WhyNotHugo** [comment]
FWIW, this is also an issue on desktop when I have a another window below Telegram.

I've simply learnt to always give Telegram more space if I want to type on it, but there's nothing phone-specific about the issue (though there's no workaround on a phone).

I'm not sure about X11, but on Wayland this is by design, from [xdg_toplevel::set_min_size](https://wayland.app/protocols/xdg-shell#xdg_toplevel:request:set_min_size):

> The client should not rely on the compositor to obey the minimum size. The compositor may decide to ignore the values set by the client and request a smaller size.

I understand that you're not talking to Wayland directly, and using Qt as an intermediate, and the problem is that Qt's abstraction promises something different. But FYI, that promise is broken because it is not possible to uphold.

I know on floating desktops a window can be larger than the screen and you can just drag then up and down to see the "off-screen" parts, but there's no such concept on tiling desktops: windows are always rendered in their entirety, never partially and they never overlap. So if there's not enough space, they will be made smaller.

**Comment by ilya-fedin** [comment]
The problem here is not Qt but no development will in having a re-design that fits smaller screens. Even if tdesktop was talking to Wayland directly, this particular issue would exist as we just can't handle smaller sizes.

**Comment by WhyNotHugo** [comment]
I think we're not seeing eye to eye on the "minimum size" issue.

I understand that as part of Telegram's design, you want Telegram's window to always be larger than a minimum size. This expectation can be met on a few specific scenarios (basically, on a stacking compositor/desktop), but it's just unrealistic anywhere else.

On my particular scenario (a tiling compositor), if I want to have a window below Telegram, then the vertical space left for Telegram is less than its minimum height. In such a scenario, how would you enforce a minimum height? There's literally no more pixels left on screen. This isn't about a "small screen" either; my screen is 34" (3440x1400px) but I might want to have something below telegram. See example screenshot:

![image](https://user-images.githubusercontent.com/730811/233342311-cc8cb4cd-7aed-4408-92e2-f7985c91379f.png)

Note that in this specific scenario, it's perfectly feasible to render the chat-history widget smaller; it would still be able to fit plenty of content.

**Comment by ilya-fedin** [comment]
> Note that in this specific scenario, it's perfectly feasible to render the chat-history widget smaller; it would still be able to fit plenty of content.

No doubt it's possible, the problem is there's no development will. Just lowering the limits will lead to visual artifacts what was already proven in the past. The reality is tdesktop needs work from someone interested to fix the widgets to handle such sizes, likely with redesigning various place (there's not only the chat history, but also settings view and etc, etc, etc all of which has to be fixed as well before the limit could be lowered).

> but I might want to have something below telegram

tdesktop is just not optimized for such use-case, sorry, but you can't use it like that.

> how would you enforce a minimum height?

As it currently does on Wayland: by rendering outside of the window. If you want correct operation, you have to enlarge the window. It's better than crashing, do you agree? And we can't do anything better without massive changes.

> but it's just unrealistic anywhere else.

Such use-cases are just unsupported, sorry. You're losing your warranty when bypassing application's requirements.

**Comment by ilya-fedin** [comment]
Also, as we won't crash anymore, it will also be possible to handle that with a "Please increase your window size" plumb like was proposed in #25539. The question is whether this is something @john-preston would like to have though.

**Comment by WhyNotHugo** [comment]
> The reality is tdesktop needs work from someone interested to fix the widgets to handle such sizes, likely with redesigning various place (there's not only the chat history, but also settings view and etc, etc, etc all of which has to be fixed as well before the limit could be lowered).

C++ is far outside my area of expertise, so I doubt I'll ever be able to contribute that much. Maybe someday someone coming across this issue will have the right skill-sets to address this. :crossed_fingers: 

> You're losing your warranty when bypassing application's requirements.

What exactly re the requirements? "The window must be at least X size"? :joy: 

> it will also be possible to handle that with a "Please increase your window size" plumb like was proposed in https://github.com/telegramdesktop/tdesktop/issues/25539. The question is whether this is something @john-preston would like to have though.

I don't really that that this is worth the effort. I'd rather just leave the issue open until someone has the time+skill to address is properly. At least now it works for _reading_ a conversation.

**Comment by gurucubano** [comment]
El día miércoles, octubre 18, 2023 a las 01:19:39 -0700, Ellie escribió:

> Can't you mark this as confirmed or something? It won't just "disappear" just because the misguided GitHub action is designed to assume so.
> 

+1

-- 
Matthias Apitz, ✉ ***@***.***, http://www.unixarea.de/ +49-176-38902045
Public GnuPG key: http://www.unixarea.de/key.pub

**Comment by Aokromes** [comment]
> Can't you mark this as confirmed or something? It won't just "disappear" just because the misguided GitHub action is designed to assume so.

you know, a lot of issues are fixed and forgoten to close related issue, this helps us to find those.

**Comment by ell1e** [comment]
> a lot of issues are fixed and forgoten to close related issue, this helps us to find those.

I see, I guess that makes sense. In any case, I just checked on my Linux phone and this bug is definitely very not fixed. The minimum window size would need to be probably more than half the height it is now for landscape mode, with scrollbars added accordingly.

**Comment by ell1e** [comment]
Fwiw: 1. there isn't really a technical difference of a small Linux tablet and a large Linux phone, the distinction is somewhat arbitrary. 2. maybe there could be a consideration to make all platforms, including Android/iOS, be based on the same codebase so that this issue is solved? A Linux phone isn't really different to an Android phone either so there's no reason why one would need to be based on the desktop client that apparently nobody wants to make fit, and the other gets an entirely separate code base where it *is* made to fit, when it's definitely possible to just share the code and make it work everywhere.

**Comment by ell1e** [comment]
Well, my point was if the code bases weren't separate they would already be accidentally supported now and nobody would have to do custom work on it. The work for tablet touch support on "desktop'ish" stuff is already done, the work on phone factor UI scaling as well, yet for some reason it just happens to be split up. Qt runs on phones, or so I thought, so I don't quite understand it.

**Comment by ilya-fedin** [comment]
> the work on phone factor UI scaling as well

That's just false. The inability of the UI to fit smaller sizes is exactly the reason the limit exists.

**Comment by Aokromes** [comment]
i tried to play a bit with scalling and with 175% system interface and 150% interfaz scalling shows properly. now i don't remember what was the bugged scalling settings xd

**Comment by ilya-fedin** [comment]
> If the codebases weren't split

The point is this couldn't have happen. The Android client was written before tdesktop and tdesktop was adopted. Even now tdesktop lags behind mobile clients a lot due to the low-levelity of C++, it's considered to provide bad UX for modern native features due to Qt's focus on embedded and it's considered bugged due to lots of bugs in Qt. I don't imagine how other clients could be deprecated in sight of all that but I can imagine tdesktop can get deprecated for Unigram & TelegramSwift as they both provide native UX and their development speed is much faster, their developers are able to implement all features in time

**Comment by ell1e** [comment]
For what it's worth, most Electron stuff runs horribly on my phone. So that would have been in practice even worse. But you mention other frameworks, there's also dart and flutter I think. I hope one day this can be solved such that everything works on all devices of all sizes.

**Comment by ilya-fedin** [comment]
Running on Linux phones is not a goal and Electron is perfect for desktops

**Comment by ilya-fedin** [comment]
> I hope one day this can be solved such that everything works on all devices of all sizes

Don't hope, native clients without using frameworks are likely to be always preferred by Telegram. That was a requirement in all contests so far (Telegram X for Android, the web clients).

**Comment by ell1e** [comment]
Okay, but that wouldn't unify the codebases then at all. Since Electron isn't perfect at all for phones. Even for desktop, I beg to differ, I have countless out of memory crashes of electron apps and yeah, they're really not working great if they run for a while.

**Comment by ilya-fedin** [comment]
Yeah, that's the point, I don't understand why do you think codebase unifying is a goal. It's very much the other way around: internal competition is welcome as you can see and native solutions are likely to replace cross-platform ones. That's perhaps bad for Linux due to the low market share, it can lose official support.

**Comment by ell1e** [comment]
Unifying the code bases is useful because then issues like this one don't crop up. If you gatekeep and separate features per device and ecosystem based on how that device *usually* looks like (but not always!) you end up with scattered stuff that would actually be useful everywhere, just split up. It also increases the maintenance burden. It also doesn't mean that someone will go "I'll add that, but I don't want to add it twice, so only fork X gets it".

**Comment by ilya-fedin** [comment]
I haven't asked why that's useful, I said that it doesn't seem to be a goal and is unlikely to change. The native UX and the lightweight due to the lack of a cross-platform framework seem to be considered more important than having to do less work. If you can do more work for better result and have money for that then why not after all.

**Comment by ell1e** [comment]
Then I don't understand this discussion. I was merely expressing one way to solve it while also solving other issues, I think that's fair to bring up.

**Comment by ilya-fedin** [comment]
This isnot realistic because people who can decide on tha

**Comment by ell1e** [comment]
So what's the point of the bugtracker then?

**Comment by ilya-fedin** [comment]
This bugtracker is only for tdesktop, it's not platform-wide and any propositions that require the involvement of someone else don't really fit here. If you have a proposition to solve that inside if tdesktop (like a PR fixing the actual places that don't fit smaller sizes) then it's ok. If you propose some restructurization between multiple clients then it's out of scope.

**Comment by ilya-fedin** [comment]
Actually the only real goal is to support devices with keyboard (even if they have a touch) IIRC, that's likely why this issue is not a priority. IIRC this already was written in this issue or some other.

**Comment by WhyNotHugo** [comment]
Issue has not vanished; being able to type messages on devices with smaller screens is still desirable.
