### ISSUE TITLE
'Empty message' sending multiple pictures

### ISSUE THREAD

**Issue by sovietspaceship** [telegramdesktop/tdesktop#3710]
### Steps to reproduce
1. send at least two pictures, one with ratio low enough to be normally sent as uncompressed document (i.e. 600x14), and one compressible (i.e. 512x512)
2. enter optional meme message for durov
3. send as compressed

### Expected behaviour
Should send one picture as document and the other as picture

### Actual behaviour
The uncompressed picture is shown as 'Empty message', while the other is correctly displayed.

![screenshot_2017-07-26_14 06 53](https://user-images.githubusercontent.com/18464885/28623435-e8c5b1e6-720d-11e7-8519-a2acf7057a9c.png)
![screenshot_2017-07-26_14 09 26](https://user-images.githubusercontent.com/18464885/28623440-ed13de6c-720d-11e7-9f45-bb086ae9e97a.png)

### Configuration
**Operating system:** Linux amd64

**Version of Telegram Desktop:** 1.1.15 alpha

**Used theme**: any

<details><summary><b>Logs</b>:</summary>
лол
</details>

**Comment by stek29** [comment]
Looks like it was fixed.

**Comment by sovietspaceship** [comment]
Lol no viktor check your doggo glasses, I still have the issue on 1.1.19 alpha

**Comment by stek29** [comment]
@sovietspaceship 
> Operating system: Linux amd64

Sorry, I forgot you're using a meme OS.

**Comment by stek29** [comment]
(or, in other words: Can't reproduce on macOS)

**Comment by sovietspaceship** [comment]
<sub>Times my os froze at 110 °C running react apps in a month: 0
Times andrei's macos froze at 110 °C running react apps in a day: 2</sub>

Anyway yes, it's probably system-specific. I don't have a windows machine to test this on, so if you can confirm it's only specific to linux or also applies to wandows it may be helpful.

**Comment by stek29** [comment]
@sovietspaceship nah, it's not system specific, i'm just dumb.

> <sub>react apps</sub>

<sub>please don't say they were in electron</sub>

**Comment by sovietspaceship** [comment]
Hopefully it will be fixed in a future version (;
