### ISSUE TITLE
Windows 10 native notification doesn't appear on action center

### ISSUE THREAD

**Issue by iKenshu** [telegramdesktop/tdesktop#3826]
### Steps to reproduce
1. I think you need to have WIndows 10 insider preview
2.  Go to windows store and install telegram desktop app
3.  Active native notification on settings on telegram

### Expected behavior
The native notification for Windows 10 should display a few seconds on display with the format of the native notification and also show on action center. Also, should be enabled to change on >Settings>Systeam>Notification&Actions

### Actual behavior
Sounds when I receive a new one, but it doesn't show and the app doesn't appear in >Settings>Systeam>Notification&Actions

### Configuration
Windows 10 recent builds of insider preview 16273
Telegram 1.1.18

----

I install the telegram desktop from the website(telegram.org)  and this behavior doesn't happend

**Comment by Aokromes** [comment]
Works for me on Microsoft Windows [Version 10.0.16278.1000]
http://i.imgur.com/2TV2HsG.png

**Comment by stek29** [comment]
Maybe it was fixed?

**Comment by Aokromes** [comment]
Tested on Microsoft Windows [Version 10.0.16278.1000] with telegram 1.1.18 it was broken, updating to 1.1.19 to see if it's fixed or if it was windows issue.

**Comment by iKenshu** [comment]
This still happens with the new version of telegram 1.1.22 on Windows Store

**Comment by iKenshu** [comment]
This still happening on the Windows Fall Creators Update

**Comment by ofalvai** [comment]
One useful addition: Telegram is missing from the app list in Settings -> System -> Notifications & actions

**Comment by iKenshu** [comment]
This only happened now with the version in the Windows Store

**Comment by kimfranken** [comment]
I still have this problem with the Windows Store version (1.2.6). Not sure why this is closed.

**Comment by emavgl** [comment]
I notice the same problem here with the Windows Store version (1.2.6) and Windows 10.0.16299 build 16299. Telegram doesn't show pop-up notification (I tried with both Windows-style notification and with the standard one).

**Comment by Aokromes** [comment]
#2318 ?
