### ISSUE TITLE
Font issues

### ISSUE THREAD

**Issue by arronges** [telegramdesktop/tdesktop#3910]
### Steps to reproduce
1. Open Telegram window and watch.

### Expected behaviour
Message font should be renderd correctly.

### Actual behaviour
The text rendered by Telegram (since last week update) looks distorted. No matter what language or display resolution is choosen, the text looks like that seen in this issue:
https://github.com/telegramdesktop/tdesktop/issues/1037
but that doesn't concern Russian language only; it concerns English text as well.
Also, it does concern entire UI, including disalogs and list of contacts on the left.

Another person's complained on Reddit of exactly the same problem:
https://www.reddit.com/r/Telegram/comments/3vhsls/font_issue_for_telegram_on_windows_7_10/

The problem seems to disapear when I set 150% UI scale, but it's surely not good solution and in fact not a solution at all, just a termporary hack. It's almost impossible to work, please fix it asap. It's basic functionality and it works incorrectly.

### Configuration
**Operating system:**
Windows 7 (build 7601 SP1)

**Version of Telegram Desktop:**
Version 1.1.23

**Used theme**:
Windows: Windows 7 Aero (irrelevant, I've tried Aero and Classic Themes).
Telegram: Night mode (irrelevant to the problem -- it persists in both Day and Night modes).

**Comment by auchri** [comment]
There was no update last week?

https://github.com/telegramdesktop/tdesktop/releases

**Comment by auchri** [comment]
I fixed your links btw.

**Comment by arronges** [comment]
I don't know exactly what week what was that update, but I took update last week and font rendering got broken. Now I seem to have the latest version and this issue still persists.

Thank you for fixing links.

**Comment by auchri** [comment]
Did you try the solution postet at Reddit?

> My graphics drivers were up to date, I just did a clean install of W10 and it fixed it.

**Comment by arronges** [comment]
Well, it's almost impossible to do, because we have corporate Win7s installed and managed by company administration.

**Comment by arronges** [comment]
Just a note to say, I didn't install games nor heavy graphics apps, I work with VisualStudio 15 / VmWare. Admins keep the Windows up to date. Just checked the video drivers and they're up to date. However I should say that most of the computers do not have this problem with Telegram.

**Comment by arronges** [comment]
Example of the font rendring issue (with English text):
![image](https://user-images.githubusercontent.com/32126891/30641010-1b7ed2ee-9e0e-11e7-8707-0d77f1f92d80.png)

**Comment by john-preston** [comment]
@arronges Can you try some previous versions from github.com/telegramdesktop/tdesktop/releases? Like 1.1.0 perhaps. And see if it works the same or better.

**Comment by arronges** [comment]
Sorry for delay, I was trying several versions and failed to find the one that looks OK. May be some shared libraries have been installed and now even proper versions of Telegram use them for rendering.

**Comment by arronges** [comment]
Just checked 1.1.0 and 1.0.38. Same issues with the font.

**Comment by falcn** [comment]
I have same issue over RDP. Telegram looks like in @arronges screenshot, text is barely readable.

I also found a workaround.
1) close telegram process and disconnect
2) change client RDP settings to use 8-bit color
3) connect and start Telegram with a 8-bit color
4) disconnect, edit client settings to use 32-bit color again
5) reconnect. Text in telegram looks clear and readable

Of course, it's bad solution: I cannot just tell every user to follow this instruction just to start Telegram Desktop

**Comment by falcn** [comment]
Another (bad) workaround is to disable font smoothing over rdp in "Administrative Templates->Windows Components->Remote Desktop Services->Remote Desktop Session Host->Remote Session Environment->Do not allow font smoothing"

**Comment by kolyambo** [comment]
Same issue, waiting for fix. It's impossible to work over rdp in telegram...

**Comment by rinebrie** [comment]
Hi guys, I fixed that problem by switching color depth settings from **16-bit** to a "32-bit".

I have a notebook with "Intel HD Graphics 3000" graphics card.

![sol](https://user-images.githubusercontent.com/51261945/58747641-34f6dd80-8498-11e9-9deb-a0147de3ac5b.png)

**Comment by rinebrie** [comment]
Thanks to @falcn for the solution!

I fixed that problem by switching graphics card color depth settings from 16-bit to a 32-bit.

![sol](https://user-images.githubusercontent.com/51261945/58747694-ec8bef80-8498-11e9-9a5d-a8b4799e80d4.png)

**Comment by falcn** [comment]
@rinebrie unfortunately can't do that on a Hyper-V virtual machine.
Waiting for a fix

**Comment by Aokromes** [comment]
this issue is still valid on 1.9.8?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
