### ISSUE TITLE
Can't write anymore :D because it appears emoji list

### ISSUE THREAD

**Issue by ArmeF97** [telegramdesktop/tdesktop#4511]
### Steps to reproduce
1. Write :D 
2. Press CTRL+ENTER (the key I use to send)

### Expected behaviour
:D is sent.

### Actual behaviour
Not sent, in the textbox there is a sad emoji

### Configuration
**Operating system:** Win 10

**Version of Telegram Desktop:** 1.2.12 alpha

**Used theme**: Default

**Comment by stek29** [comment]
fixed in b6e7625016431af3d4829eb4888cf2fad60e6544

**Comment by ralesk** [comment]
Another, probably better solution might have been not to preselect the top hit in the emoji suggestion box, so merely typing whatever you want (be it `:d` or `:D`) works as supposed to — and then if you _do_ actually want an emoji, you can just press down and enter to select.

Or not trigger on single letter ones, but that might be a little bit awkward for heavy emoji users.

**Comment by netman69** [comment]
this still happens for me in 1.2.14, but only if text typed before the emoji

**Comment by ArmeF97** [comment]
@netman69 , happens to me too

**Comment by stek29** [comment]
See #4528
