### ISSUE TITLE
Crash when opening profile from group members list

### ISSUE THREAD

**Issue by Senderman** [telegramdesktop/tdesktop#4560]
### Steps to reproduce
1. Open group members list
2. Press right mouse key on any member
3. Click "Open Profile"

### Expected behaviour
The profile opens
### Actual behaviour
Telegram crashes with segmentation fault
### Configuration
**Operating system:**
Arch Linux
**Version of Telegram Desktop:**
1.2.15
**Used theme**:
Night

**Comment by Aokromes** [comment]
I suggest you to run Telegram alpha under gdb to get a crashlog.

**Comment by stek29** [comment]
> Version of Telegram Desktop:
> 1.2.15

What about 1.2.17 at least?

**Comment by Senderman** [comment]
> What about 1.2.17 at least?
Still crashes

**Comment by prototype99** [comment]
Operating system:
gentoo Linux
Version of Telegram Desktop:
1.2.17
Used theme:
Night

i'm getting nothing. there must be something it interacts with that causes that issue.

**Comment by Senderman** [comment]
> i'm getting nothing. there must be something it interacts with that causes that issue.

I don't know what can iteract. Just in case, I've uploaded a [video](https://www.youtube.com/watch?v=Wxj0IJBl42w.) with that bug

**Comment by Sea-n** [comment]
@stek29 With latest alpha (v24): #4758

**Comment by stek29** [comment]
(reposting crash report tag here)

Report Tag: `a4b59e59-4f47-436e-924d-3fe8e373e0a4`
User Tag: `b11e5853dd2cfce6`

**Comment by Senderman** [comment]
Report Tag: f673b052-5500-48dd-8d1d4ba9-a3ce98ec
User Tag: 22e074a8e234c83c

**Comment by prototype99** [comment]
yeah just watched the video, i can definitely do that fine, so considering we both are using a form of linux there must be something gentoo does differently that prevents it. the more difficult thing to work out, will be what. as far as i know, i don't actually have any patches, so mine should be near to just the vanilla source code

**Comment by john-preston** [comment]
Strange crash. I hope I've fixed it in https://github.com/telegramdesktop/tdesktop/commit/2878e46d2bd86cbc430bce3c1ad8ffcb55718d4e

**Comment by Senderman** [comment]
Telegram alpha 1.3. Still crashes. I also switched from Cinnamon DE to GNOME, but this didn't help so I think problem not on my side. Just in case, I've reported crash again
Report tag:  `f836c0fb-7ac1-42ef-df0408bf-db1acdb2`
User tag: `22e074a8e234c83c`

**Comment by john-preston** [comment]
@Senderman Please try the version 1.3.1 (autoupdate your alpha version) and then send the report if it still is crashing. I hope that I've fixed that in https://github.com/telegramdesktop/tdesktop/commit/2878e46d2bd86cbc430bce3c1ad8ffcb55718d4e

**Comment by Senderman** [comment]
Tdesktop 1.3.1 is still crashing
Report tag `c48480ff-12b6-4a9d-449e24a6-d2739e48`

**Comment by Senderman** [comment]
1.3.1 crashes
Report tag `530a78f1-6946-454b-602c77b6-8dd7ed38`
User tag `22e074a8e234c83c`

**Comment by john-preston** [comment]
@Senderman Thanks, I've reproduced that! I'll fix that in the next version.
