### ISSUE TITLE
Windows Telegram Desktop 1.5.15 freezes when trying to change user rights in group chat

### ISSUE THREAD

**Issue by Lorkes** [telegramdesktop/tdesktop#5698]
### Steps to reproduce
1. Go to user restriction menu
2. Click on "Send messages" or "Send media" (only those two items, others work fine)

### Expected behaviour
User's "Send message" or "Send media" rights should toggle

### Actual behaviour
Telegram client CPU usage grows to ~40% and it completely freezes (so I have to kill the process)

### Configuration
**Operating system:**
Windows 8.1
**Version of Telegram Desktop:**
1.5.15
**Used theme**:
Matrix

**Comment by john-preston** [comment]
@Lorkes Thanks for your report! And what are group permissions?

**Comment by Lorkes** [comment]
![image](https://user-images.githubusercontent.com/39070506/52901210-8ab4bc00-3200-11e9-914e-302f181a67ed.png)

The strange thing is that in android app it shows "Send stickers & GIFs" permission turned off.
Also, the same happens on Debian 9, Telegram Desktop 1.5.15

**Comment by john-preston** [comment]
I hope this was fixed in https://github.com/telegramdesktop/tdesktop/commit/5ec80238a0d5b9076f880d7a3ca616696a726dc9

We'll see in the next version.

**Comment by Aokromes** [comment]
> My telegram desktop freezes a lot as well since the last time I updated it. It wasn't like this before the update. I'm using Windows 10 Home Version 1909. 8G Ram. Intel Core i7 6500U. And Telegram Desktop Version 2.0.1. It's absolutely normal except when I start typing in the white textarea at the bottom of the chats. Every two or three words I type it freezes for a second or two and then again I can type two or three words and it freezes for a second or two and so on.

your looks more spell checker than rights.

**Comment by aderchox** [comment]
> > My telegram desktop freezes a lot as well since the last time I updated it. It wasn't like this before the update. I'm using Windows 10 Home Version 1909. 8G Ram. Intel Core i7 6500U. And Telegram Desktop Version 2.0.1. It's absolutely normal except when I start typing in the white textarea at the bottom of the chats. Every two or three words I type it freezes for a second or two and then again I can type two or three words and it freezes for a second or two and so on.
> 
> your looks more spell checker than rights.

I don't get what you're saying exactly, but if you mean it might be because of the "spell checker", I just enabled "Choose System Spell Checker"(It was disabled by default) and the problem still persists. I've also disabled animations and emoji replacement with no success.

**Comment by Lorkes** [comment]
> > > My telegram desktop freezes a lot as well since the last time I updated it. It wasn't like this before the update. I'm using Windows 10 Home Version 1909. 8G Ram. Intel Core i7 6500U. And Telegram Desktop Version 2.0.1. It's absolutely normal except when I start typing in the white textarea at the bottom of the chats. Every two or three words I type it freezes for a second or two and then again I can type two or three words and it freezes for a second or two and so on.
> > 
> > 
> > your looks more spell checker than rights.
> 
> I don't get what you're saying exactly, but if you mean it might be because of the "spell checker", I just enabled "Use System Spell Checker"(It was disabled by default) and the problem still persists. I've also disabled animations and emoji replacement with no success.

You should open your own issue, it's not related to mine and it's already closed.
