### ISSUE TITLE
[Question] How to exclude archived chats in unread count ?

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#6314]

**Comment by xazos79** [comment]
I have the same problem. On the app its fine and archived chat unread counts are excluded from the app logo badge count. However on desktop, they are included in the windows 10 task bar badge count.

**Comment by SmartManoj** [comment]
Resolved

**Comment by zouden** [comment]
@SmartManoj this issue is not resolved. Archived chats still contribute to your unread messages count in the taskbar.

**Comment by SmartManoj** [comment]
![image](https://user-images.githubusercontent.com/7231077/100493898-f52eb600-3161-11eb-9bc1-e8443b7f3a24.png)
I am fine to exclude muted chats

**Comment by zouden** [comment]
This issue is about archived chats, not muted chats. We need the same option for archived chats.

**Comment by ololoepepe** [comment]
It's a shame that copy-pasting one switch and adding one if-statement is such a big deal

**Comment by Iowerth** [comment]
Almost 6 years... Can anyone tell devs how to realize this feature?

**Comment by paolodelfino** [comment]
If it may help to remove the notifications count badge of Archived chats, not total notifications count addition (or whatever it is, I didn't test), here's how, but good luck with compiling time: https://gist.github.com/paolodelfino/7e2bd02f596b8827cf85af11325f2cb3.

**Comment by paul1149** [comment]
Unsubbing because the author is not interested, or maybe this is a premium feature.
