### ISSUE TITLE
fonts in filepicker dialog

### ISSUE THREAD

**Issue by LiohMoeller** [telegramdesktop/tdesktop#6340]
### Steps to reproduce
1. Open Telegram
2. Start a chat
3. Select the filepicker to upload

### Expected behaviour
The fonts in the filepicker dialog should be displayed correctly

### Actual behaviour
The fonts in the filepicker are not displayed correctly:

![telegram_filepicker](https://user-images.githubusercontent.com/1267594/61998645-4a147500-b0b3-11e9-8a28-63b7af1a9576.png)

### Configuration
**Operating system:**
Slackware -current

**Version of Telegram Desktop:**
1.7.14

**Used theme**:
default

**Comment by xuzhao9** [comment]
Similar issue, but on the KDE platform, openSUSE Tumbleweed, tdesktop version 1.8.15.
Screenshot:
![image](https://user-images.githubusercontent.com/502017/68093869-60775d00-fe68-11e9-8f85-093452a68dc6.png)

**Comment by remcohaszing** [comment]
I did the following:

- Opened Telegram
- Opened the side menu
- Navigated to _Settings_ → _Chat Settings_→ _Edit theme_
- Clicked the menu icon button in the edit color palette
- Clicked _Show palette file_ — This opened Nautilus file browser with messed up fonts
- From Nautilus I opened my terminal emulator, which also had messed up fonts
- Ran `env | sort` in the messed up emulator
- Ran `env | sort` in another terminal emulator
- Compared the results using Meld.

I found out the following environment variable was injected by Telegram.

```sh
FONTCONFIG_FILE=/home/remco/.local/share/TelegramDesktop/tdata/fc-custom-1.conf
```

I opened another program using the same command, and found out this is indeed the variable that messes up fonts.

```sh
FONTCONFIG_FILE="$HOME/.local/share/TelegramDesktop/tdata/fc-custom-1.conf" eog
```

I believe these lines are the culprit:

https://github.com/telegramdesktop/tdesktop/blob/f75bfb436934aac0bc1fda029a6119bf3b0f67e7/Telegram/SourceFiles/platform/linux/specific_linux.cpp#L54-L60

**Comment by Aokromes** [comment]
maybe you don't have installed ttf-opensans?

**Comment by remcohaszing** [comment]
I didn’t, but now I do. It doesn’t make a difference.

I don’t think it should matter though. Why should Telegram use a custom font for its system dialogs and subprocesses anyway?

**Comment by Aokromes** [comment]
try on 1.9.8

**Comment by xuzhao9** [comment]
The bug is fixed on 1.9.8 on my environment.

**Comment by remcohaszing** [comment]
The issue persists for me on version 1.9.8. I also tried using beta version 1.9.9, on which the issue also persists.

**Comment by remcohaszing** [comment]
I also tried deleting `/.local/share/TelegramDesktop/tdata/fc-custom-1.conf`, but that didn't work.

**Comment by Aokromes** [comment]
@remcohaszing what linux you use with what DE?

**Comment by remcohaszing** [comment]
I use Pop!_OS 19.10 and Adwaita dark theme. It’s basically the same as Ubuntu.

**Comment by Aokromes** [comment]
i see it like this on freshly installed: https://i.imgur.com/ejyFgeM.png

**Comment by Aokromes** [comment]
test on 1.9.17.

**Comment by remcohaszing** [comment]
It appears to be fixed now.
