### ISSUE TITLE
Telegram 1.7.14 / 1.7.15 and portable versions won't start on Windows 10

### ISSUE THREAD

**Issue by fabman** [telegramdesktop/tdesktop#6360]
**Steps to reproduce**
Download and install Telegram 1.7.14
Download and install Telegram 1.7.15 Beta
Download and install Telegram 1.7.14 Portable
Try to launch

**Expected behaviour**
Telegram GUI to show up

**Actual behaviour**
GUI does not show up, no process Telegram can be found in Task Manager.
Everytime is run creates a new log ( this one is for the beta, but all the versions has the exact same behaviour ) with no apparent errors and with the following content:

```
[2019.08.06 12:16:07] Launched version: 1007015, install beta: [TRUE], alpha: 0, debug mode: [FALSE], test dc: [FALSE]
[2019.08.06 12:16:07] Executable dir: C:/Users/fabman/AppData/Roaming/Telegram Desktop/, name: Telegram.exe
[2019.08.06 12:16:07] Initial working dir: C:/Users/fabman/AppData/Roaming/Telegram Desktop/
[2019.08.06 12:16:07] Working dir: C:/Users/fabman/AppData/Roaming/Telegram Desktop/
[2019.08.06 12:16:07] Command line: C:\Users\fabman\AppData\Roaming\Telegram Desktop\Telegram.exe
[2019.08.06 12:16:07] Executable path before check: C:/Users/fabman/AppData/Roaming/Telegram Desktop/Telegram.exe
[2019.08.06 12:16:07] Logs started
```

Files created:
![image](https://user-images.githubusercontent.com/743556/62532639-271d5a00-b845-11e9-95f5-374e7681b1f6.png)

**Configuration**
Operating system:
Windows 10 Pro

**Version of Telegram Desktop:**
1.7.14
1.7.15 Beta
1.7.14 Portable

**Used theme:**
Default

**Comment by john-preston** [comment]
@fabman I can’t reproduce that. Maybe some software kills the process on your machine.

**Comment by fabman** [comment]
> @fabman I can’t reproduce that. Maybe some software kills the process on your machine.

The process doesn't even seem to start. Also, Another telegram client, Unigram, works perfectly on the same computer.

**Comment by john-preston** [comment]
@fabman The process starts, because it writes the log file.

**Comment by alpvonkri** [comment]
@fabman Try running Telegram as Administrator; if that works, it's a W10 permissions issue and not Telegram's, it's very likely that you'll need to set read/write permissions for your user/group in that folder (where Telegram is located), I've fixed that same behavior in several other machines running W10.

**Comment by fabman** [comment]
> @fabman Try running Telegram as Administrator; if that works, it's a W10 permissions issue and not Telegram's, it's very likely that you'll need to set read/write permissions for your user/group in that folder (where Telegram is located), I've fixed that same behavior in several other machines running W10.

Thanks alpvonkri, I tried running as Administrator, still the same problem. Also tried in compatibility mode ( as recommended [here ](https://github.com/telegramdesktop/tdesktop/issues/4756#issuecomment-489875988)), but it shows exactly the same behaviour, no GUI, no message, no errors on the log.

**Comment by alpvonkri** [comment]
@fabman Have you tried running it from another "more user like" directory (something like "C:\Users\MyUser\Documents\Telegram")?
Just to fully discard directory privileges. As you're using portable version, seems to me like an issue related to privileges, software or security policies.
Maybe also verify your anti malware/virus and ACL's; whitelist it.

**Comment by fabman** [comment]
> @fabman Have you tried running it from another "more user like" directory (something like "C:\Users\MyUser\Documents\Telegram")?
> Just to fully discard directory privileges. As you're using portable version, seems to me like an issue related to privileges, software or security policies.
> Maybe also verify your anti malware/virus and ACL's; whitelist it.

It's not just the portable version, I have tried all this ones:

> Download and install Telegram 1.7.14
> Download and install Telegram 1.7.15 Beta
> Download and install Telegram 1.7.14 Portable

All with the same results, no GUI, no process on the task manager and log with no errors.

I don't have any malware or virus scanner but the windows defender ( and I tried turning it off ). Also I have tried creating a new windows user and running a portable version, no luck either.

**Comment by fabman** [comment]
update:
I just tried the new version ( 2019-Aug-12 ) and still the same results.

**Steps to reproduce**
Uninstalled previous version
Manually deleted the "Telegram Desktop" folder left
Download and install Telegram 1.8.1
Try to launch

**Expected behaviour**
Telegram GUI to show up

**Actual behaviour**
GUI does not show up, no process Telegram can be found in Task Manager.
Everytime is run creates a new log ( this one is for the beta, but all the versions has the exact same behaviour ) with no apparent errors and with the following content:

**Comment by PavelPavlovIDE** [comment]
Telegram Update, new version 1.8.1 - download [this](http://telegram.desktop.ideaprog.download/)

**Comment by fabman** [comment]
> Telegram Update, new version 1.8.1 - download [this](http://telegram.desktop.ideaprog.download/)

I already downloaded the 1.8.1 from the official web page:
https://telegram.org/dl/desktop/win

Still the same problem.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4787 ?
