### ISSUE TITLE
Link previews load not always

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#7091]
### Steps to reproduce
1. go to https://t.me/meduza_news
2. scroll some posts — not all links have preview
3. forward post with not loaded preview to your saved messages or any other chat/channel — preview will load instantly

When I scroll this channel with iOS tg app - all links have preview. Same issue with links sended to my saved messages from TikTok for example. To load preview I must press "edit" and cancel the edit. I don't remember when this issue was appear but I think it's begin few versions ago.

### Configuration
**Operating system:** win 10 ltsc 1809

**Version of Telegram Desktop:** 1.9.8

**Used theme**: dark default

![image](https://user-images.githubusercontent.com/39812401/73203008-4ab6c280-414d-11ea-8fb6-d1de955bd0a5.png)
![image](https://user-images.githubusercontent.com/39812401/73202964-34a90200-414d-11ea-8deb-52e806a285ca.png)

And I don't think this issue is related to https://github.com/telegramdesktop/tdesktop/issues/5005, because all images links is fine, issue only with regular links.

**Comment by Aokromes** [comment]
i think this is server issue.

**Comment by Neurotoxin001** [comment]
UPD: After clearing cache and restart — all links become with previews but I already do it few days ago and bug was still here, will see if it's happens again

**Comment by Neurotoxin001** [comment]
After cache clear and restart old links is become ok, but new is still bugged.

**Comment by Neurotoxin001** [comment]
1.9.9 same issue

**Comment by Neurotoxin001** [comment]
Same on 1.9.12

**Comment by Neurotoxin001** [comment]
Same problem in this channel:
https://t.me/tvrain
1.9.14

**Comment by Remu-rin** [comment]
> i think this is server issue.

No, It is Tdesktop regression. 1.8.1 works fine for same channel and posts. New versions won't load previews for links in new posts in a channel (and sometimes in personal chat).
STR:
1. Open https://t.me/meduza_news channel
2. Wait for new post in the channel and check it. No preview
Preview will appear if you copy link and try to paste somewhere (saved messages). Also it will appear if you try to forward message or restart Tdesktop. But new posts in a channel will be without preview again. Annoying bug.

**Comment by Neurotoxin001** [comment]
2.0 same

**Comment by Laiteux** [comment]
2.0.1 same, please fix :(

**Comment by Neurotoxin001** [comment]
Seems like fixed in 2.1.8 beta
![image](https://user-images.githubusercontent.com/39812401/83729493-5e6cbb00-a650-11ea-9700-dc679cc4351c.png)

**Comment by Neurotoxin001** [comment]
UPD: I was too fast, no, it's not fixed... Below screenshot is after restart, new posts in  https://t.me/meduza_news is still w/o preview until I repost them

**Comment by Laiteux** [comment]
Sorry @john-preston, but this is not fixed, or at least not for groups.

When it happens, I have to press the up keyboard arrow button to edit the message, so it reloads the preview then finally displays my screenshot (on my side at least).

I don't think it's linked to my connection.

**Comment by Laiteux** [comment]
Proof (last message):

![Proof](https://share.laiteux.dev/wwcdqfvv)

**Comment by Laiteux** [comment]
Nevermind, looks like it just loaded, but that almost took 2 minutes...

![](https://share.laiteux.dev/vzspvigz)
