### ISSUE TITLE
In message double-dash replaced with long single dash. 

### ISSUE THREAD

**Issue by Alexnder** [telegramdesktop/tdesktop#738]
This '--' replaced to '—'
Ex. This:
mysqldump --host=localhost --user=root
Sended as:
mysqldump —host=localhost —user=root

**Comment by peterfarrell** [comment]
We've noticed this too. Makes sharing command line code via telegram a bit odd.

**Comment by overjt** [comment]
fixed

![imagen](https://i.imgur.com/57NbqlU.png)

**Comment by draeath** [comment]
Still a problem here - OSX version 0.8.38

**Comment by Alexnder** [comment]
Not fixed:
![image](https://cloud.githubusercontent.com/assets/1038313/9327990/6e959488-45ad-11e5-8292-930ddf365d92.png)

**Comment by auchri** [comment]
Duplicate #522

**Comment by cleanrat** [comment]
I would be grateful for returning (yep) the auto-conversion of double hyphens into dashes. What Alexnder wrote about was not about normal sentences but about programming code or code-like strings such as console commands or conifiguration parameters. Those should normally be formatted with monospace font.

Therefore, I suggest the following:

- If a double hyphen is formatted with monospace font, then keep it as double hyphen.
- Otherwise convert double hyphens into dashes.

I suppose that Telegram was not primarily made for programmers but mainly for ordinary users who would like to send each other neatly formatted messages. If some users need to send each other code or code-like strings, they will have to ensure that their messages are formatted accordingly.

**Comment by cleanrat** [comment]
It doesn't :( I have just upgraded Telegram 1.1.23 to 1.3.7 on Ubuntu. Auto-conversion _did_ work in the old version and it _does not_ work in the new one. An example of what I am typing:
> qwe -- rty
After sending, this text is displayed exactly as I typed it — with double hyphens. I expected a dash to be displayed instead.

**Comment by john-preston** [comment]
@cleanrat It should be replaced while you type your two dashes, not when you send them.

**Comment by cleanrat** [comment]
Well, it isn't... Neither when I'm typing nor when I've sent a message. Before this update, double hyphens used to be replaced after sending, now they are not any more. What extra information can I provide for you to analyze my issue? I'm on Xubuntu 16.04.4.

**Comment by john-preston** [comment]
@cleanrat Those replacements are switched on and off by "Replace emoji" checkbox in Settings, perhaps you need to switch it on.

**Comment by cleanrat** [comment]
Thank you! I'd never have guessed that I need to change that setting... Not too obvious. It would be great to change its title to something like "Replace emoji and special characters on typing" to avoid stupid questions like mine from other users. Thanks again for your time and help.
