### ISSUE TITLE
Unable to move Telegram window

### ISSUE THREAD

**Issue by remcohaszing** [telegramdesktop/tdesktop#7419]
### Steps to reproduce
1. Use Telegram on Linux
2. Minimize Telegram and do other things
3. Reopen Telegram
4. Repeat the steps above until…
5. You realize the Telegram window can’t be moved around

### Expected behaviour
The Telegram can be moved around like any other window.

### Actual behaviour
The Telegram window suddenly can’t be moved around anymore. All other interactions still work, such as using the application, resizing, moving the window to another display.

What doesn’t work is dragging the window around using the title bar or `<Super>+mouse drag`, and maximizing.

### Configuration
**Operating system:** Pop_OS! 19.10

**Version of Telegram Desktop:** 1.9.21

**Used theme**: Custom

**Comment by omkarnathsingh** [comment]
This is working fine for me on Ubuntu. Can you please re-try or provide more information? Try once on latest version.

**Comment by remcohaszing** [comment]
I added a screencast to show what’s happening. At the beginning of the recording, I am unable to move the Telegram aroung. After restarting it, I am able to move the window around.

I think this only happens when Telegram is minimized to the tray. I’m not 100% sure, though, because I keep Telegram minimized most of the time.

Also the screencast shows the Telegram tray icon has been replaced in the beginning by a weird icon. This might be related.

This also shows I use a triple monitor setup. I don’t know if that’s related either.

I really want to provide more info, but I don’t know what more info you need.

[Screencast_2020-03-30_14:09:16.zip](https://github.com/telegramdesktop/tdesktop/files/4402540/Screencast_2020-03-30_14.09.16.zip)

**Comment by blkmlk** [comment]
I have the same issue. @remcohaszing Do you use any extensions?

**Comment by remcohaszing** [comment]
I updated to Pop!_OS 20.04 yesterday, so I can’t tell for sure if the issue still persists.

I have recently switched to Qt5 based Audacious 4 as my media player, which suffers the same isue.

I use the following GNOME extensions:

- [Applications Overview Tooltip](https://extensions.gnome.org/extension/1071/applications-overview-tooltip)
- [Dash to Dock](https://extensions.gnome.org/extension/307/dash-to-dock)
- [EasyScreenCast](https://extensions.gnome.org/extension/690/easyscreencast) (Installed from source)
- [GSConnect](https://extensions.gnome.org/extension/1319/gsconnect)
- [GTK Title Bar](https://extensions.gnome.org/extension/1732/gtk-title-bar)
- [Mpris Indicator Button](https://extensions.gnome.org/extension/1379/mpris-indicator-button)
- Pop Shell (System extension)
- System76 Power (System extension)
- Ubuntu AppIndicators (System extension)

**Comment by blkmlk** [comment]
From your list of extensions, I use only GTK Title Bar. Maybe this extension breaks something?

**Comment by remcohaszing** [comment]
This issue is a bit hard to troubleshoot, as I can’t reproduce it on purpose. I’ll give feedback if it happens again, or if it doesn’t occur this week.

**Comment by remcohaszing** [comment]
I haven’t run into this issue last last week. I suppose it has been resolved by updating tot Ubuntu / Pop!_OS 20.04.

**Comment by blkmlk** [comment]
No, updating to 20.04 doesn't resolve the issue in my case. I still have this problem

**Comment by hailwood** [comment]
I have the same issue and also use GTK title bar, it's likely a conflict between Telegram and that extension.

However I do not have this issue with any other app, so it's definitely something specific to Telegram and not just the extension at fault.

**Comment by ilya-fedin** [comment]
> However I do not have this issue with any other app, so it's definitely something specific to Telegram and not just the extension at fault.

Looks like it is specific to qt rather then to telegram https://github.com/velitasali/GTKTitleBar/issues/22#issuecomment-644635483

**Comment by hailwood** [comment]
This issue actually appears to be corrected for me. Not sure what's changed :)

**Comment by ilya-fedin** [comment]
Maybe due to custom decorations?

**Comment by hailwood** [comment]
Ah yes, likely fixed in v2.1.19

> * Custom window title bar works in all Linux versions.

**Comment by antonio-petricca** [comment]
Same issue for me!
