### ISSUE TITLE
Enhancement: Hide photo viewer overlay after zooming an image

### ISSUE THREAD

**Issue by aleksusklim** [telegramdesktop/tdesktop#7931]
### Is your feature request related to a problem?

Often photos have a long textual description, or sent as album. In this case, after clicking on it, the internal image viewer will show both description (shortened) and two of other photos from this album.

This interactive information will stay on screen until some timeout (about 3 sec) and then slowly fade. But only if no user mouse input was detected! So, for example, if you want to pan zoomed-in image, you will trigger displaying of this interface, which might overlap some important parts of the picture.

Waiting for it to disappear every time is not convenient.

### Describe the solution you'd like

Disable _any_ onscreen controls in image viewer if this picture was zoomed-in. Especially right after pressing the middle mouse button.

When a photo zoom is restored to default (second middle click) or just made smaller than screen-fit size (Ctrl + Wheel Down) the behavior of on-screen controls should remain as it is currently (instantly visible with fade timeout).

### Describe alternatives you've considered

There is another possible way to hide all interactive controls: by implementing a dedicated button that will toggle them.

For example, it could be a square labeled "i" ('information' icon), located in top-left corner of this overlay, just like 'X' button is located at tor-right corner currently.

By default after restart of Telegram Desktop client, the state of overlay should be globally visible. This 'i'-button will be visible too (and will fade-out just like other buttons).

When clicked, all of other buttons, links and texts on overlay should disappear, but only this button ought to stay on screen (semi-transparent like 'X'-close) and continue to conform the 3-sec timeout (so eventually it will fade-out, but mouse move will restore it).

Second click on 'i'-button will toggle display of overlay back. The state of overlay visibility should be kept global (for all images and chars) until Telegram Desktop restarts.

When main buttons on overlay are hidden, the image viewer should still accept any keyboard shortcuts to navigate: for example, Left/Right arrow to open next photo, Ctrl+S to save, and Escape to exit picture view mode.

Another possibility would be a context menu entry for image overlay, titled "Hide controls" initially, but "Show controls" when this function was already used to hide the overlay.

### Configuration

**Operating system:** Windows 7 SP1
**Version of Telegram Desktop:** 2.1.6
**Used theme**: Day

### Additional context

Here are some screenshots of the issue: (with 125% interface scale)

**photo with description:**

Initial:
![description - initial](https://user-images.githubusercontent.com/13969463/82644750-4007c800-9c2b-11ea-9ce2-ee87a183ad47.png)

Default:
![description - default](https://user-images.githubusercontent.com/13969463/82644776-4f871100-9c2b-11ea-8882-412edc9aadb8.png)
_(Note that semi-transparent box with description text and links could still severely interfere with image content)_

Timeout:
![description - timeout](https://user-images.githubusercontent.com/13969463/82644795-5746b580-9c2b-11ea-9604-087fb1e5a684.png)
_(And you should hold your mouse very still, to be able to read it like this)_

**photo albums:**

Initial:
![album - initial](https://user-images.githubusercontent.com/13969463/82644809-5f065a00-9c2b-11ea-9267-e0657ba94625.png)

Default:
![album - default](https://user-images.githubusercontent.com/13969463/82644834-675e9500-9c2b-11ea-8d8b-c9a7568b7371.png)
_(Note that almost opaque album previews also interfere with content)_

Zoomed to the bottom:
![album - zoomed](https://user-images.githubusercontent.com/13969463/82644863-72192a00-9c2b-11ea-9f0f-b5ab29b28c27.png)
_(The main issue: even after zooming in picture manually, this unnecessary overlay still visible)_

So it would be very logically to hide overlays on zoom, since if user had zoomed – then he want to see a part of image, and not the text/album previews, which should become visible again after zooming out.

**Comment by aleksusklim** [comment]
Э, я те сча закрою, ага!

**Comment by aleksusklim** [comment]
Брысь!

Telegram Desktop 2.7.4, issue still relevant.

**Comment by john-preston** [comment]
I'd accept a PR for that one.

**Comment by aleksusklim** [comment]
Done, https://github.com/telegramdesktop/tdesktop/pull/16303

**Comment by ad3ph-spare** [comment]
Hey! Did this ever lead to any change? Sadly I still experience the need for this enhancement

**Comment by Aokromes** [comment]
unless you mean something else, it's already done:

![Image](https://github.com/user-attachments/assets/8d9c30dc-9a08-4f00-8900-1ca62675301c)

![Image](https://github.com/user-attachments/assets/0db7fea8-f737-4470-8638-2fb0634e7d9d)
