### ISSUE TITLE
Segmentation fault when attaching and detaching external display

### ISSUE THREAD

**Issue by fotonmoton** [telegramdesktop/tdesktop#796]
Get segmentation fault when attaching or detaching external display.
Steps to reproduse the problem:
1. Start Telegram
2. Attach or detach external display
3. Get segfault

**System**:
DISTRIB = "Linux Mint 17.1 Rebecca"
cinnamon = 2.4.8+rebecca
kernel = 3.13.0-37-generic #64-Ubuntu
xorg = 1:7.7+1ubuntu8.1
Telegram = 0.8.21

**logs**:
```
Jun  5 16:54:04 machine colord: Device added: xrandr-Ancor Communications Inc-ASUS VH222-A2LMTF033121
Jun  5 16:54:05 machine kernel: [93117.169157] Telegram[20580]: segfault at 28 ip 0000000000a05a71 sp 00007fff1d7fdab0 error 4 in Telegram[400000+2181000]
Jun  5 16:58:08 machine kernel: [93360.715719] Telegram[20980]: segfault at 28 ip 0000000000a05a71 sp 00007fff69232d10 error 4 in Telegram[400000+2181000]
Jun  5 16:58:08 machine colord: device removed: xrandr-Ancor Communications Inc-ASUS VH222-A2LMTF033121
```

**program logs**:
```
/opt/Telegram/Telegram 
libs init..
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Segmentation fault
```

**Comment by Foodfast** [comment]
I newbie in gdb? but anyway, think this maybe help:
```
run
Starting program: /opt/Telegram/Telegram 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
libs init..
[New Thread 0x7ffff4d0c700 (LWP 21714)]
[New Thread 0x7fffefdf9700 (LWP 21715)]
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
[Thread 0x7fffefdf9700 (LWP 21715) exited]
[Thread 0x7ffff4d0c700 (LWP 21714) exited]
[Inferior 1 (process 21710) exited normally]

```

**Comment by auchri** [comment]
Maybe related to #77

**Comment by Aokromes** [comment]
@Foodfast you forgot to run the needed commands

i sugest you to run gdb with the next script:

```code
set logging overwrite on
set logging file backtrace.log
handle SIG33 pass nostop noprint
set pagination 0
set logging on
echo \n--- DEBUG: --- START\n\n
run
echo \n--- DEBUG: BACKTRACE FULL\n\n
backtrace full
echo \n--- DEBUG: INFO REGISTERS\n\n
info registers
echo \n--- DEBUG: CALLS (x/32i $pc)\n\n
x/32i $pc
echo \n--- DEBUG: THREAD APPLY ALL BACKTRACE\n
thread apply all backtrace
echo \n--- DEBUG: --- STOP\n\n
set logging off
quit

**Comment by Foodfast** [comment]
@Aokromes 
**bt**:
```
(gdb) bt
#0  0x0000000000a05a71 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
#1  0x0000000000a0612c in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
#2  0x0000000000a05fa4 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
#3  0x0000000000a05fa4 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
#4  0x0000000000a052ea in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
#5  0x0000000000c8fde3 in QWidgetBackingStore::doSync() ()
#6  0x0000000000c90159 in QWidgetBackingStore::sync() ()
#7  0x00000000009f5d90 in QWidgetPrivate::syncBackingStore() ()
#8  0x0000000000a0b65c in QWidget::event(QEvent*) ()
#9  0x0000000000ae000b in QMainWindow::event(QEvent*) ()
#10 0x00000000009e029c in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    ()
#11 0x00000000009e5290 in QApplication::notify(QObject*, QEvent*) ()
#12 0x00000000016000b5 in QCoreApplication::notifyInternal(QObject*, QEvent*)
    ()
---Type <return> to continue, or q <return> to quit---
#13 0x0000000000c9105f in QWidgetBackingStore::sendUpdateRequest(QWidget*, QWidgetBackingStore::UpdateTime) ()
#14 0x0000000000c91b75 in QWidgetBackingStore::markDirty(QRect const&, QWidget*, QWidgetBackingStore::UpdateTime, QWidgetBackingStore::BufferState) ()
#15 0x0000000000a2063c in QWidgetWindow::repaintWindow() ()
#16 0x0000000001630a72 in QMetaObject::activate(QObject*, int, int, void**) ()
#17 0x0000000000fb0bda in QWindowPrivate::emitScreenChangedRecursion(QScreen*)
    ()
#18 0x0000000000fb5aa1 in QWindowPrivate::setTopLevelScreen(QScreen*, bool) ()
#19 0x0000000000fb6d66 in QWindow::screenDestroyed(QObject*) ()
#20 0x0000000001630477 in QMetaObject::activate(QObject*, int, int, void**) ()
#21 0x00000000016311ed in QObject::destroyed(QObject*) ()
#22 0x00000000016396ea in QObject::~QObject() ()
#23 0x0000000000fda621 in QScreen::~QScreen() ()
#24 0x0000000000f9a8aa in QPlatformScreen::~QPlatformScreen() ()
#25 0x0000000000d63389 in QXcbScreen::~QXcbScreen() ()
#26 0x0000000000d5c719 in QXcbConnection::updateScreens() ()
#27 0x0000000000d5d2a6 in QXcbConnection::handleXcbEvent(xcb_generic_event_t*)
    ()
#28 0x0000000000d5e43b in QXcbConnection::processXcbEvents() ()
#29 0x0000000001631d96 in QObject::event(QEvent*) ()
#30 0x00000000009e029c in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    ()
---Type <return> to continue, or q <return> to quit---
#31 0x00000000009e5290 in QApplication::notify(QObject*, QEvent*) ()
#32 0x0000000001602d00 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
#33 0x0000000001655f53 in postEventSourceDispatch(_GSource*, int (*)(void*), void*) ()
#34 0x00007ffff6fb8e04 in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#35 0x00007ffff6fb9048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#36 0x00007ffff6fb90ec in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#37 0x000000000165605c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#38 0x00000000015fded1 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
#39 0x000000000160582b in QCoreApplication::exec() ()
#40 0x000000000043fa86 in main ()
```
**bt full**:
```
(gdb) bt full
#0  0x0000000000a05a71 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
No symbol table info available.
#1  0x0000000000a0612c in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
No symbol table info available.
#2  0x0000000000a05fa4 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
No symbol table info available.
#3  0x0000000000a05fa4 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
No symbol table info available.
#4  0x0000000000a052ea in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
No symbol table info available.
#5  0x0000000000c8fde3 in QWidgetBackingStore::doSync() ()
No symbol table info available.
#6  0x0000000000c90159 in QWidgetBackingStore::sync() ()
No symbol table info available.
#7  0x00000000009f5d90 in QWidgetPrivate::syncBackingStore() ()
---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#8  0x0000000000a0b65c in QWidget::event(QEvent*) ()
No symbol table info available.
#9  0x0000000000ae000b in QMainWindow::event(QEvent*) ()
No symbol table info available.
#10 0x00000000009e029c in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    ()
No symbol table info available.
#11 0x00000000009e5290 in QApplication::notify(QObject*, QEvent*) ()
No symbol table info available.
#12 0x00000000016000b5 in QCoreApplication::notifyInternal(QObject*, QEvent*)
    ()
No symbol table info available.
#13 0x0000000000c9105f in QWidgetBackingStore::sendUpdateRequest(QWidget*, QWidgetBackingStore::UpdateTime) ()
No symbol table info available.
#14 0x0000000000c91b75 in QWidgetBackingStore::markDirty(QRect const&, QWidget*, QWidgetBackingStore::UpdateTime, QWidgetBackingStore::BufferState) ()
No symbol table info available.
#15 0x0000000000a2063c in QWidgetWindow::repaintWindow() ()
No symbol table info available.
#16 0x0000000001630a72 in QMetaObject::activate(QObject*, int, int, void**) ()
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#17 0x0000000000fb0bda in QWindowPrivate::emitScreenChangedRecursion(QScreen*)
    ()
No symbol table info available.
#18 0x0000000000fb5aa1 in QWindowPrivate::setTopLevelScreen(QScreen*, bool) ()
No symbol table info available.
#19 0x0000000000fb6d66 in QWindow::screenDestroyed(QObject*) ()
No symbol table info available.
#20 0x0000000001630477 in QMetaObject::activate(QObject*, int, int, void**) ()
No symbol table info available.
#21 0x00000000016311ed in QObject::destroyed(QObject*) ()
No symbol table info available.
#22 0x00000000016396ea in QObject::~QObject() ()
No symbol table info available.
#23 0x0000000000fda621 in QScreen::~QScreen() ()
No symbol table info available.
#24 0x0000000000f9a8aa in QPlatformScreen::~QPlatformScreen() ()
No symbol table info available.
#25 0x0000000000d63389 in QXcbScreen::~QXcbScreen() ()
No symbol table info available.
#26 0x0000000000d5c719 in QXcbConnection::updateScreens() ()
No symbol table info available.
#27 0x0000000000d5d2a6 in QXcbConnection::handleXcbEvent(xcb_generic_event_t*)
    ()
---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#28 0x0000000000d5e43b in QXcbConnection::processXcbEvents() ()
No symbol table info available.
#29 0x0000000001631d96 in QObject::event(QEvent*) ()
No symbol table info available.
#30 0x00000000009e029c in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    ()
No symbol table info available.
#31 0x00000000009e5290 in QApplication::notify(QObject*, QEvent*) ()
No symbol table info available.
#32 0x0000000001602d00 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
No symbol table info available.
#33 0x0000000001655f53 in postEventSourceDispatch(_GSource*, int (*)(void*), void*) ()
No symbol table info available.
#34 0x00007ffff6fb8e04 in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#35 0x00007ffff6fb9048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#36 0x00007ffff6fb90ec in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#37 0x000000000165605c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
No symbol table info available.
#38 0x00000000015fded1 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
No symbol table info available.
#39 0x000000000160582b in QCoreApplication::exec() ()
No symbol table info available.
#40 0x000000000043fa86 in main ()
No symbol table info available.
```

**Comment by Aokromes** [comment]
Ok, you have compiled on release mode, compile on debug mode on that way @telegramdesktop can see better crashlog.

**Comment by Foodfast** [comment]
recive update of Telegram version 0.8.21, but bug still here.

**Comment by Foodfast** [comment]
@Aokromes sorry but I don`t compiled Telegram, I have binary version from site :) Ok, try to compile from source.

**Comment by Foodfast** [comment]
@Aokromes Cant compile Telegram on debug mode. When compiling MetaEmoji.pro with this [tutorial](https://github.com/telegramdesktop/tdesktop/blob/master/QTCREATOR.md#building-telegram-desktop) I've got this error:
```
/home/foton/TBuild/tdesktop/Telegram/SourceFiles/_other/genemoji.cpp:39: error: #error Only Mac OS X is supported
 #error Only Mac OS X is supported
```

**Comment by Foodfast** [comment]
@Aokromes can you give me binary telegram with debug mode?

**Comment by Foodfast** [comment]
Can anyone give me version with extended  debug messages? Or maybe I think wrong way and I must compile Telegram only myself?

**Comment by Streppel** [comment]
@Foodfast see [this](https://github.com/telegramdesktop/tdesktop/pull/746) pull request. Maybe try to remove the #else statement and see if it compiles correctly?

**Comment by Foodfast** [comment]
@Streppel yeah, this help! Thanks a lot! And about bug, I'm not sure but it seems I doing something wrong :) I complie debug version of Telegram (againg thanks to @Streppel) and here output of gdb:
```
gdb ./Telegram 
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./Telegram...done.
(gdb) run
Starting program: /home/foton/TBuild/tdesktop/Linux/Debug/Telegram 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
libs init..
[New Thread 0x7ffff30d3700 (LWP 11131)]
[New Thread 0x7ffff22b8700 (LWP 11132)]
[New Thread 0x7ffff1831700 (LWP 11133)]
[New Thread 0x7fffe32ae700 (LWP 11134)]
[Thread 0x7fffe32ae700 (LWP 11134) exited]
[New Thread 0x7fffe32ae700 (LWP 11135)]
[Thread 0x7fffe32ae700 (LWP 11135) exited]
[New Thread 0x7fffe32ae700 (LWP 11136)]
[Thread 0x7fffe32ae700 (LWP 11136) exited]
[New Thread 0x7fffe32ae700 (LWP 11137)]
[New Thread 0x7fffdeaac700 (LWP 11138)]
[New Thread 0x7fffde1e0700 (LWP 11139)]
[New Thread 0x7fffdd9df700 (LWP 11140)]
[Thread 0x7fffdeaac700 (LWP 11138) exited]
[New Thread 0x7fffdd124700 (LWP 11141)]
[New Thread 0x7fffcf815700 (LWP 11142)]

Program received signal SIGSEGV, Segmentation fault.
0x0000000000a0a161 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
(gdb) bt full
#0  0x0000000000a0a161 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
No symbol table info available.
#1  0x0000000000a0a81c in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
No symbol table info available.
#2  0x0000000000a0a694 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
No symbol table info available.
#3  0x0000000000a0a694 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
No symbol table info available.
#4  0x0000000000a099da in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
No symbol table info available.
#5  0x0000000000c94733 in QWidgetBackingStore::doSync() ()
No symbol table info available.
#6  0x0000000000c94aa9 in QWidgetBackingStore::sync() ()
No symbol table info available.
#7  0x00000000009fa4a0 in QWidgetPrivate::syncBackingStore() ()
No symbol table info available.
#8  0x0000000000a0fd3c in QWidget::event(QEvent*) ()
No symbol table info available.
#9  0x0000000000ae46ab in QMainWindow::event(QEvent*) ()
No symbol table info available.
#10 0x00000000009e49ec in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
No symbol table info available.
#11 0x00000000009e9990 in QApplication::notify(QObject*, QEvent*) ()
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#12 0x00000000015195e5 in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
No symbol table info available.
#13 0x0000000000c9599f in QWidgetBackingStore::sendUpdateRequest(QWidget*, QWidgetBackingStore::UpdateTime) ()
No symbol table info available.
#14 0x0000000000c964b5 in QWidgetBackingStore::markDirty(QRect const&, QWidget*, QWidgetBackingStore::UpdateTime, QWidgetBackingStore::BufferState) ()
No symbol table info available.
#15 0x0000000000a24d8c in QWidgetWindow::repaintWindow() ()
No symbol table info available.
#16 0x0000000001549fa2 in QMetaObject::activate(QObject*, int, int, void**) ()
No symbol table info available.
#17 0x0000000000ee808a in QWindowPrivate::emitScreenChangedRecursion(QScreen*) ()
No symbol table info available.
#18 0x0000000000eecf41 in QWindowPrivate::setTopLevelScreen(QScreen*, bool) ()
No symbol table info available.
#19 0x0000000000eee206 in QWindow::screenDestroyed(QObject*) ()
No symbol table info available.
#20 0x00000000015499a7 in QMetaObject::activate(QObject*, int, int, void**) ()
No symbol table info available.
#21 0x000000000154a71d in QObject::destroyed(QObject*) ()
No symbol table info available.
#22 0x0000000001552c1a in QObject::~QObject() ()
No symbol table info available.
#23 0x0000000000f11971 in QScreen::~QScreen() ()
No symbol table info available.
#24 0x0000000000ed1d7a in QPlatformScreen::~QPlatformScreen() ()
No symbol table info available.
#25 0x0000000000d3d709 in QXcbScreen::~QXcbScreen() ()
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#26 0x0000000000d36aa9 in QXcbConnection::updateScreens() ()
No symbol table info available.
#27 0x0000000000d37636 in QXcbConnection::handleXcbEvent(xcb_generic_event_t*) ()
No symbol table info available.
#28 0x0000000000d387cb in QXcbConnection::processXcbEvents() ()
No symbol table info available.
#29 0x000000000154b2b6 in QObject::event(QEvent*) ()
No symbol table info available.
#30 0x00000000009e49ec in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
No symbol table info available.
#31 0x00000000009e9990 in QApplication::notify(QObject*, QEvent*) ()
No symbol table info available.
#32 0x000000000151c230 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
No symbol table info available.
#33 0x000000000156f4a3 in postEventSourceDispatch(_GSource*, int (*)(void*), void*) ()
No symbol table info available.
#34 0x00007ffff5594e04 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#35 0x00007ffff5595048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#36 0x00007ffff55950ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#37 0x000000000156f5ac in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
No symbol table info available.
#38 0x0000000001517401 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
No symbol table info available.
#39 0x000000000151ed59 in QCoreApplication::exec() ()
No symbol table info available.
#40 0x0000000000435bb0 in main (argc=1, argv=0x7fffffffe068) at ../../Telegram/SourceFiles/main.cpp:73
---Type <return> to continue, or q <return> to quit---
        a_cnt = 1
        a_argv = {0x7fffffffe39d "/home/foton/TBuild/tdesktop/Linux/Debug/Telegram", 0x0}
        app = {<PsApplication> = {<QApplication> = {<No data fields>}, static staticMetaObject = {d = {
                superdata = 0x26b3520 <QApplication::staticMetaObject>, 
                stringdata = 0x1dd9160 <qt_meta_stringdata_PsApplication>, 
                data = 0x1dd91a0 <qt_meta_data_PsApplication>, 
                static_metacall = 0x893442 <PsApplication::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}}, <RPCSender> = {_rpcDoneHandlers = {q_hash = {{
                  d = 0x1fbf0a0 <QHashData::shared_null>, e = 0x1fbf0a0 <QHashData::shared_null>}}}, 
            _rpcFailHandlers = {q_hash = {{d = 0x1fbf0a0 <QHashData::shared_null>, 
                  e = 0x1fbf0a0 <QHashData::shared_null>}}}}, static staticMetaObject = {d = {
              superdata = 0x26a2280 <PsApplication::staticMetaObject>, 
              stringdata = 0x1dda460 <qt_meta_stringdata_Application>, 
              data = 0x1ddaae0 <qt_meta_data_Application>, 
              static_metacall = 0x8939c0 <Application::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, photoUpdates = {d = 0x1ffc360 <QMapDataBase::shared_null>}, 
          killDownloadSessionTimes = {d = 0x1ffc360 <QMapDataBase::shared_null>}, killDownloadSessionsTimer = 
    {<QTimer> = {<No data fields>}, static staticMetaObject = {d = {
                superdata = 0x26f28c0 <QTimer::staticMetaObject>, 
                stringdata = 0x1dee5e0 <qt_meta_stringdata_SingleTimer>, 
                data = 0x1dee6a0 <qt_meta_data_SingleTimer>, 
                static_metacall = 0x89f992 <SingleTimer::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, _finishing = 0, _inited = false}, serverName = {
            static null = {<No data fields>}, d = 0x28fba10}, socket = <incomplete type>, socketRead = {
            static null = {<No data fields>}, d = 0x1fbd960 <QArrayData::shared_null>}, 
          server = <incomplete type>, clients = {d = 0x1fbd960 <QArrayData::shared_null>}, closing = false, 
          lastActionTime = 34332928, window = 0x291ad10, updateRequestId = 0, 
          updateManager = <incomplete type>, updateReply = 0x0, 
          updateCheckTimer = {<QTimer> = {<No data fields>}, static staticMetaObject = {d = {
---Type <return> to continue, or q <return> to quit---
                superdata = 0x26f28c0 <QTimer::staticMetaObject>, 
                stringdata = 0x1dee5e0 <qt_meta_stringdata_SingleTimer>, 
                data = 0x1dee6a0 <qt_meta_data_SingleTimer>, 
                static_metacall = 0x89f992 <SingleTimer::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, _finishing = 29584654, _inited = true}, updateThread = 0x0, 
          updateDownloader = 0x0, writeUserConfigTimer = <incomplete type>, _translator = 0x2925720}
        args = {{d = 0x28b6d90}}
        a_argc = 1
        _init = {<No data fields>}
        result = 0
(gdb) q
``` 
And something more out of this topic. It seems bug in the Qt, because when I attach and detach display with runnig Qt creator it also get segfault.

**Comment by Foodfast** [comment]
similar [bug](https://bugreports.qt.io/browse/QTBUG-42985) in Qt bugtracker. Seems this bug resolved in Qt 5.5 and Telegram compiles with Qt 5.4. Maybe problem around Qt versions&

**Comment by Foodfast** [comment]
Yeah, I was right about "it seems I doing something wrong". I compiled Qt in debug mode and run script, that @Aokromes suggest. In this case [output](https://gist.github.com/Foodfast/60378929ed6f0f4a80c1) looks more informative.

**Comment by Aokromes** [comment]
:) yeah indeed, that's true debug mode. I hope that helps @telegramdesktop to fix the crash :)

**Comment by Foodfast** [comment]
I hope too. But related to this #807 topic @telegramdesktop not so "open minded" :) Maybe it's by reason of security or so, who knows. As for me, it's bad strategy for open-source development. As @mbinoimi says in that topic it causes "wasting community efforts" and I totally agree with him.

**Comment by Foodfast** [comment]
Maybe [this](https://codereview.qt-project.org/#/c/84773/) patch will help. I will try to compile qt with it.

**Comment by auchri** [comment]
is it fixed with qt 5.5?

**Comment by thomich** [comment]
whats about this.. could it be fixed or not? on my station not.. still crash if plugout the external monitor...

**Comment by Aokromes** [comment]
thomich: https://github.com/telegramdesktop/tdesktop/issues/796#issuecomment-126911564

**Comment by ffix** [comment]
I've built v0.9.2 with qt5.5 but issue is still here.

The traceback is [there](https://gist.github.com/ffix/7e531eaad6d095393eda).

**Comment by telegramdesktop** [comment]
@ffix Traceback looks like a Qt issue :( not a single call is from tdesktop call (except initial main()). Or some simple Qt project instead of tdesktop does not crash in this case (using exact the same Qt build)?

**Comment by telegramdesktop** [comment]
@ffix *is from tdesktop code

**Comment by fotonmoton** [comment]
Can't reproduce segfault in version 0.10.11. Seems like bug is gone.

**Comment by zaps166** [comment]
Fixed since Qt 5.6.0: https://github.com/qt/qtbase/commit/a094af001795c9651b299d700a992150d1aba33a

**Comment by ruslan-k** [comment]
i had segfault at 30 ip 0000000002999a96 sp 00007fe4e4826730 error 4 in telegram[400000+5af6000] on Xubuntu 18.04, 5.3.0-40 kernel
