### ISSUE TITLE
crash on openSUSE after update

### ISSUE THREAD

**Issue by jkarpio** [telegramdesktop/tdesktop#8026]
### Steps to reproduce
1. run telegram
2. it never open

### OS Details
Operating System: openSUSE Tumbleweed 20200511
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.70.0
Qt Version: 5.14.1
Kernel Version: 5.6.11-1-default
OS Type: 64-bit
Processors: 4 × Intel® Core™ i7-5500U CPU @ 2.40GHz
Memory: 7.7 GiB of RAM

**Version of Telegram Desktop:**
Latest available after update

**Installation source (Linux Only)** 
Oficial telegram release from website

**Used theme**:
default

<details><summary><b>Logs</b>:</summary>

[2020.06.08 23:38:06] Launched version: 2001011, install beta: [FALSE], alpha: 0, debug mode: [FALSE], test dc: [FALSE]
[2020.06.08 23:38:06] Executable dir: /home/carpio/bin/Telegram/, name: Telegram
[2020.06.08 23:38:06] Initial working dir: /home/carpio/bin/Telegram/
[2020.06.08 23:38:06] Working dir: /home/carpio/.local/share/TelegramDesktop/
[2020.06.08 23:38:06] Command line: ./Telegram --help
[2020.06.08 23:38:06] Executable path before check: /home/carpio/bin/Telegram/Telegram
[2020.06.08 23:38:06] Logs started
[2020.06.08 23:38:06] Launcher filename: telegramdesktop.desktop
[2020.06.08 23:38:06] Checking for XDG Desktop Portal...
[2020.06.08 23:38:06] XDG Desktop Portal is present!
[2020.06.08 23:38:06] Getting DE, XDG_CURRENT_DESKTOP: 'KDE'
[2020.06.08 23:38:06] Getting DE, DESKTOP_SESSION: '/usr/share/wayland-sessions/plasmawayland'
[2020.06.08 23:38:06] Getting DE, KDE_SESSION_VERSION: '5'
[2020.06.08 23:38:06] DE: KDE5
[2020.06.08 23:38:06] Using XDG Desktop Portal.
[2020.06.08 23:38:06] Connecting local socket to /run/user/1000/adb37404721d35b32571863b881b041e-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
[2020.06.08 23:38:06] Socket connect error 0, starting server and app...
[2020.06.08 23:38:06] Moved logging from '/home/carpio/.local/share/TelegramDesktop/log_start0.txt' to '/home/carpio/.local/share/TelegramDesktop/log.txt'!
[2020.06.08 23:38:06] Opened '/home/carpio/.local/share/TelegramDesktop/tdata/working' for reading, the previous Telegram Desktop launch was not finished properly :( Crash log size: 2924
[2020.06.08 23:38:06] Update Info: MTP is unavailable.
[2020.06.08 23:38:07] App Error: _basePath is empty in writeSettings()
[2020.06.08 23:38:07] Primary screen DPI: 96
[2020.06.08 23:38:07] Found non-trivial Device Pixel Ratio: 2
[2020.06.08 23:38:07] Environmental variables: QT_DEVICE_PIXEL_RATIO=''
[2020.06.08 23:38:07] Environmental variables: QT_SCALE_FACTOR=''
[2020.06.08 23:38:07] Environmental variables: QT_AUTO_SCREEN_SCALE_FACTOR=''
[2020.06.08 23:38:07] Environmental variables: QT_SCREEN_SCALE_FACTORS=''
[2020.06.08 23:38:07] Error: failed to load 'gdk_set_allowed_backends' function!

Using Wayland-EGL
Using the 'xdg-shell' shell integration

(Telegram:4028): GLib-GObject-WARNING **: 23:34:33.829: cannot register existing type 'GdkDisplayManager'

(Telegram:4028): GLib-CRITICAL **: 23:34:33.829: g_once_init_leave: assertion 'result != 0' failed

(Telegram:4028): GLib-GObject-CRITICAL **: 23:34:33.829: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

(Telegram:4028): GLib-GObject-WARNING **: 23:34:33.829: invalid (NULL) pointer instance

(Telegram:4028): GLib-GObject-CRITICAL **: 23:34:33.829: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(Telegram:4028): GLib-GObject-WARNING **: 23:34:33.829: invalid (NULL) pointer instance

(Telegram:4028): GLib-GObject-CRITICAL **: 23:34:33.829: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(Telegram:4028): GLib-GObject-WARNING **: 23:34:33.830: cannot register existing type 'GdkDisplay'

(Telegram:4028): GLib-CRITICAL **: 23:34:33.830: g_once_init_leave: assertion 'result != 0' failed

(Telegram:4028): GLib-GObject-CRITICAL **: 23:34:33.830: g_type_register_static: assertion 'parent_type > 0' failed

(Telegram:4028): GLib-CRITICAL **: 23:34:33.830: g_once_init_leave: assertion 'result != 0' failed

(Telegram:4028): GLib-GObject-CRITICAL **: 23:34:33.830: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
Segmentation fault (core dumped)
</details>

**Comment by Seil0** [comment]
I can reproduce this crash running KDE Plasma under Wayland. If I switch to Plasma X11 Telegram works as expected.

### OS Information
Operating System: openSUSE Tumbleweed 20200611
KDE Plasma Version: 5.19.0
KDE Frameworks Version: 5.70.0
Qt Version: 5.15.0
Kernel Version: 5.6.14-1-default
OS Type: 64-bit
Processors: 16 × AMD Ryzen 7 3700X 8-Core Processor
Memory: 15,5 GiB
Graphics Processor: AMD Radeon ™ RX 480 Graphics 

### Version of Telegram Desktop:
latest available

### Installation source (Linux Only)
official telegram release

**Comment by imjasonmiller** [comment]
Might this be related to #8005?

I'm running Arch and anything > `2.1.7` doesn't open.

**Comment by ilya-fedin** [comment]
> Might this be related to #8005?

Yes, this is related to the situation that I explained here: https://github.com/telegramdesktop/tdesktop/issues/8005#issuecomment-640505114

**Comment by Seil0** [comment]
> Yes, this is related to the situation that I explained here: #8005 (comment)

So it should be fixed once libwayland is updated (#8031) ?

**Comment by ilya-fedin** [comment]
> So it should be fixed once libwayland is updated (#8031) ?

This updates libwayland in the github action and instruction
To be fixed in the release binary, libwayland should be updated by the person who builds them

**Comment by jkarpio** [comment]
Still crashing after update on Wayland

Using Wayland-EGL
Using the 'xdg-shell' shell integration

(Telegram:21323): GLib-GObject-WARNING **: 18:59:36.675: cannot register existing type 'GdkDisplayManager'

(Telegram:21323): GLib-CRITICAL **: 18:59:36.675: g_once_init_leave: assertion 'result != 0' failed

(Telegram:21323): GLib-GObject-CRITICAL **: 18:59:36.675: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

(Telegram:21323): GLib-GObject-WARNING **: 18:59:36.675: invalid (NULL) pointer instance

(Telegram:21323): GLib-GObject-CRITICAL **: 18:59:36.675: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(Telegram:21323): GLib-GObject-WARNING **: 18:59:36.675: invalid (NULL) pointer instance

(Telegram:21323): GLib-GObject-CRITICAL **: 18:59:36.675: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(Telegram:21323): GLib-GObject-WARNING **: 18:59:36.676: cannot register existing type 'GdkDisplay'

(Telegram:21323): GLib-CRITICAL **: 18:59:36.677: g_once_init_leave: assertion 'result != 0' failed

(Telegram:21323): GLib-GObject-CRITICAL **: 18:59:36.677: g_type_register_static: assertion 'parent_type > 0' failed

(Telegram:21323): GLib-CRITICAL **: 18:59:36.677: g_once_init_leave: assertion 'result != 0' failed

(Telegram:21323): GLib-GObject-CRITICAL **: 18:59:36.677: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

**Comment by ilya-fedin** [comment]
2.1.12?

**Comment by ilya-fedin** [comment]
Can't reproduce on
```
Operating System: openSUSE Tumbleweed 20200618
KDE Plasma Version: 5.19.0
KDE Frameworks Version: 5.71.0
Qt Version: 5.15.0
Kernel Version: 5.7.1-1-default
```
With Plasma (Full Wayland) session and 2.1.12

**Comment by a-dekker** [comment]
It doesn't crash when using Plasma (**Full** Wayland), but it does crash with the above error when selecting Plasma (Wayland) during login.

Using:
```
TDesktop 2.1.13
opensuse:tumbleweed:20200621
KDE Plasma Version: 5.19.0
Kernel version: 5.7.2-1-default
```

**Comment by ilya-fedin** [comment]
Ok, I have reproduced
