### ISSUE TITLE
Read Messages getting marked as unread everytime telegram starts.

### ISSUE THREAD

**Issue by genusistimelord** [telegramdesktop/tdesktop#8321]
### Steps to reproduce
1.  IDK how to reproduce but if you can contact me i cant show you what is occurring maybe its just something in a database not being saved properly.

### Expected behaviour
When read it should not display as unread unless i manually mark it as unread.

### Actual behaviour
A single account on my telegram messenger keeps being remarked as unread each startup of telegram. I go there to view it and nothing has changed and then it is marked as read during the duration of telegram being turned on.

### Configuration
**Operating system:Windows 10 2004**

**Version of Telegram Desktop:2.2**

**Used theme:Dark mode**

<details>
![nounreadafter checking](https://user-images.githubusercontent.com/1034709/88532961-6f440800-cfd3-11ea-802c-05b479188690.PNG)

the above is what happens after i reread it.

![unreadafterrestartPNG](https://user-images.githubusercontent.com/1034709/88532985-7bc86080-cfd3-11ea-943d-3017e8dcd535.PNG)
this is what occurs when I restart Telegram messenger each time.

</details>

**Comment by genusistimelord** [comment]
Seems in the latest version that it is now fixed?
that or it fixed itself overtime.

**Comment by alireza73uk** [comment]
I'm still having this problem and I'm on the latest version.

**Comment by genusistimelord** [comment]
I'm wondering if it randomly affect people and then goes away after a while.
